export interface ServerTrack {
  id: string;
  title: string;
  artist: string;
  album?: string;
  duration: number;
  url: string;
  coverUrl: string;
  genre: string;
  description?: string;
  isYoutube?: boolean;
  youtubeId?: string;
  createdAt?: number;
}

export const SERVER_STATIC_TRACKS: ServerTrack[] = [
  // 1. Bollywood & Sufi
  {
    id: "ar-rahman-dil-se-re",
    title: "Dil Se Re",
    artist: "A.R. Rahman",
    album: "Dil Se",
    duration: 404,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Bollywood & Sufi",
    description: "Vocal layers and acoustic perfection by A.R. Rahman.",
    isYoutube: true,
    youtubeId: "YfdfvS06v6U"
  },
  {
    id: "ar-rahman-kun-faya-kun",
    title: "Kun Faya Kun",
    artist: "A.R. Rahman",
    album: "Rockstar",
    duration: 470,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Bollywood & Sufi",
    description: "Sufi masterwork capturing pure spiritual lyricism.",
    isYoutube: true,
    youtubeId: "T94PHkuyd84"
  },
  {
    id: "arijit-singh-tum-hi-ho",
    title: "Tum Hi Ho",
    artist: "Arijit Singh",
    album: "Aashiqui 2",
    duration: 262,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Bollywood & Sufi",
    description: "The soul-stirring love anthem that redefined romantic Bollywood.",
    isYoutube: true,
    youtubeId: "Umqb9S08iaU"
  },
  {
    id: "sukhwinder-singh-chaiyya-chaiyya",
    title: "Chaiyya Chaiyya",
    artist: "Sukhwinder Singh",
    album: "Dil Se",
    duration: 414,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Bollywood & Sufi",
    description: "High-energy train-top dance classic composed by A.R. Rahman.",
    isYoutube: true,
    youtubeId: "YOYN9qNXmCw"
  },
  {
    id: "tochi-raina-kabira",
    title: "Kabira",
    artist: "Tochi Raina, Rekha Bhardwaj",
    album: "Yeh Jawaani Hai Deewani",
    duration: 251,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Bollywood & Sufi",
    description: "A calming folk-fusion blend perfect for nostalgia.",
    isYoutube: true,
    youtubeId: "jHNNMj5bNQw"
  },
  {
    id: "atif-aslam-tajdar-e-haram",
    title: "Tajdar-e-Haram",
    artist: "Atif Aslam",
    album: "Coke Studio S8",
    duration: 610,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Bollywood & Sufi",
    description: "Transcendent tribute showcasing Atif's spectacular range.",
    isYoutube: true,
    youtubeId: "a18py61_F_w"
  },
  {
    id: "arijit-singh-tujhe-kitna-chahne-lage",
    title: "Tujhe Kitna Chahne Lage",
    artist: "Arijit Singh",
    album: "Kabir Singh",
    duration: 284,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Bollywood & Sufi",
    description: "A soothing melodic reminder of pure devotion and longing.",
    isYoutube: true,
    youtubeId: "2G5rfPFIuRM"
  },
  {
    id: "arijit-singh-kesariya",
    title: "Kesariya",
    artist: "Arijit Singh",
    album: "Brahmastra",
    duration: 268,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Bollywood & Sufi",
    description: "Bright sunshine love ballad layered with saffron strokes.",
    isYoutube: true,
    youtubeId: "BddP6PYo2gs"
  },
  {
    id: "shankar-mahadevan-mitwa",
    title: "Mitwa",
    artist: "Shankar Mahadevan",
    album: "Kabhi Alvida Naa Kehna",
    duration: 382,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Bollywood & Sufi",
    description: "Sufi rock masterpiece featuring high-spirited electric leads.",
    isYoutube: true,
    youtubeId: "1SHe7OnbS60"
  },
  {
    id: "roop-kumar-rathod-maula-mere-maula",
    title: "Maula Mere Maula",
    artist: "Roop Kumar Rathod",
    album: "Anwar",
    duration: 360,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Bollywood & Sufi",
    description: "Warm spiritual prayer offering absolute peace and serenity.",
    isYoutube: true,
    youtubeId: "vX4bM_HPyAo"
  },

  // 2. Global Pop
  {
    id: "the-weeknd-blinding-lights",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    duration: 200,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Global Pop",
    description: "Sensational upbeat retro-80s synth wave soundscape.",
    isYoutube: true,
    youtubeId: "4NRXx6U8ABQ"
  },
  {
    id: "ed-sheeran-shape-of-you",
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "Divide",
    duration: 233,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Global Pop",
    description: "Marimba-infused record breaker that dominated global charts.",
    isYoutube: true,
    youtubeId: "JGwWNGJsax8"
  },
  {
    id: "the-kid-laroi-stay",
    title: "Stay",
    artist: "The Kid LAROI & Justin Bieber",
    album: "F*CK LOVE 3",
    duration: 141,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Global Pop",
    description: "Infectious upbeat pop-punk synthesizer hit.",
    isYoutube: true,
    youtubeId: "kTJczUoc26U"
  },
  {
    id: "dua-lipa-levitating",
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: 203,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Global Pop",
    description: "Infectious nu-disco groove keeping positive vibes flying high.",
    isYoutube: true,
    youtubeId: "TUVcZfQe-Kw"
  },
  {
    id: "harry-styles-as-it-was",
    title: "As It Was",
    artist: "Harry Styles",
    album: "Harry's House",
    duration: 167,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Global Pop",
    description: "Nostalgic retro-indie track with lightweight synth bells.",
    isYoutube: true,
    youtubeId: "H5v3kku4y6Q"
  },
  {
    id: "the-weeknd-starboy",
    title: "Starboy",
    artist: "The Weeknd ft. Daft Punk",
    album: "Starboy",
    duration: 230,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Global Pop",
    description: "Moody, dark house element powered by Daft Punk.",
    isYoutube: true,
    youtubeId: "34Na4j8AVgA"
  },
  {
    id: "billie-eilish-bad-guy",
    title: "Bad Guy",
    artist: "Billie Eilish",
    album: "WHEN WE ALL FALL ASLEEP",
    duration: 194,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Global Pop",
    description: "Minimalist pop utilizing baseline synthesizers.",
    isYoutube: true,
    youtubeId: "DyDfgMOUjCI"
  },
  {
    id: "ed-sheeran-perfect",
    title: "Perfect",
    artist: "Ed Sheeran",
    album: "Divide",
    duration: 263,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Global Pop",
    description: "Timeless orchestral romance ballad for sweet evenings.",
    isYoutube: true,
    youtubeId: "2Vv-BfVoq4g"
  },
  {
    id: "imagine-dragons-believer",
    title: "Believer",
    artist: "Imagine Dragons",
    album: "Evolve",
    duration: 204,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Global Pop",
    description: "High-flying stadium anthem driven by heavy drums.",
    isYoutube: true,
    youtubeId: "7wtfhZwyrcc"
  },
  {
    id: "miley-cyrus-flowers",
    title: "Flowers",
    artist: "Miley Cyrus",
    album: "Endless Summer Vacation",
    duration: 200,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Global Pop",
    description: "Ethereal self-love anthem in disco style.",
    isYoutube: true,
    youtubeId: "G7KNmW9a75Y"
  },

  // 3. Acoustic & Indie
  {
    id: "prateek-kuhad-cold-mess",
    title: "Cold / Mess",
    artist: "Prateek Kuhad",
    album: "Cold / Mess EP",
    duration: 210,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic & Indie",
    description: "Delightful warm acoustic intimacy great for healing nights.",
    isYoutube: true,
    youtubeId: "ISYg_S_HGEg"
  },
  {
    id: "vance-joy-riptide",
    title: "Riptide",
    artist: "Vance Joy",
    album: "Dream Your Life Away",
    duration: 204,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic & Indie",
    description: "Catchy ukulele melodies and beautiful storytelling.",
    isYoutube: true,
    youtubeId: "uJ_1HMUq76U"
  },
  {
    id: "passenger-let-her-go",
    title: "Let Her Go",
    artist: "Passenger",
    album: "All The Little Lights",
    duration: 252,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic & Indie",
    description: "Melancholic acoustic folk masterpiece showcasing devotion.",
    isYoutube: true,
    youtubeId: "RG73Pk1yUj8"
  },
  {
    id: "the-lumineers-ho-hey",
    title: "Ho Hey",
    artist: "The Lumineers",
    album: "The Lumineers",
    duration: 163,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic & Indie",
    description: "Rootsy acoustic stomp designed to bring smiles.",
    isYoutube: true,
    youtubeId: "zvCBSSwgt1g"
  },
  {
    id: "bon-iver-skinny-love",
    title: "Skinny Love",
    artist: "Bon Iver",
    album: "For Emma, Forever Ago",
    duration: 238,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic & Indie",
    description: "Raw cabin recording with soaring, fragile falsettos.",
    isYoutube: true,
    youtubeId: "ssdgFoHLn88"
  },
  {
    id: "death-cab-i-will-follow-you",
    title: "I Will Follow You into the Dark",
    artist: "Death Cab for Cutie",
    album: "Plans",
    duration: 195,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic & Indie",
    description: "Quiet acoustic devotion classic.",
    isYoutube: true,
    youtubeId: "NDHY1D0tKRA"
  },
  {
    id: "george-ezra-budapest",
    title: "Budapest",
    artist: "George Ezra",
    album: "Wanted on Voyage",
    duration: 200,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic & Indie",
    description: "Warm baritone vocals matching rich acoustic tempos.",
    isYoutube: true,
    youtubeId: "VHrLPs3_1Fs"
  },
  {
    id: "prateek-kuhad-kasoor",
    title: "Kasoor",
    artist: "Prateek Kuhad",
    album: "Acoustic Stories",
    duration: 192,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic & Indie",
    description: "Optimistic, sweet-strummed track exploring love.",
    isYoutube: true,
    youtubeId: "T_8mepUDeMg"
  },
  {
    id: "anuv-jain-baarishein",
    title: "Baarishein",
    artist: "Anuv Jain",
    album: "Baarishein Single",
    duration: 212,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic & Indie",
    description: "Beautiful acoustic ukelele ballad with comforting vocals.",
    isYoutube: true,
    youtubeId: "pj8vXv-L78o"
  },
  {
    id: "abdul-hannan-bikhra",
    title: "Bikhra",
    artist: "Abdul Hannan",
    album: "Bikhra Single",
    duration: 220,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic & Indie",
    description: "Dreamy subcontinental indie pop with high vocal quality.",
    isYoutube: true,
    youtubeId: "M-S09iTepZ4"
  },

  // 4. Acoustic Indie Rock
  {
    id: "local-train-choo-lo",
    title: "Choo Lo",
    artist: "The Local Train",
    album: "Aalas Ka Pedh",
    duration: 233,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic Indie Rock",
    description: "Nostalgic twilight guitar delays and anthemic rock lyrics.",
    isYoutube: true,
    youtubeId: "qN4ooNx77u0"
  },
  {
    id: "local-train-aftab",
    title: "Aftab",
    artist: "The Local Train",
    album: "Aalas Ka Pedh",
    duration: 225,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic Indie Rock",
    description: "Aesthetic slow build exploding into a giant rock climax.",
    isYoutube: true,
    youtubeId: "P9y4iS_E-Yo"
  },
  {
    id: "anuv-jain-alag-aasmaan",
    title: "Alag Aasmaan",
    artist: "Anuv Jain",
    album: "Singles Room",
    duration: 214,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic Indie Rock",
    description: "Optimistic strings carrying distance narratives gracefully.",
    isYoutube: true,
    youtubeId: "vX2cDW8yXSk"
  },
  {
    id: "coldplay-yellow",
    title: "Yellow",
    artist: "Coldplay",
    album: "Parachutes",
    duration: 269,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic Indie Rock",
    description: "Iconic sweeping guitar layers that defined stadium indie rock.",
    isYoutube: true,
    youtubeId: "yKNxeF4KMsY"
  },
  {
    id: "oasis-wonderwall",
    title: "Wonderwall",
    artist: "Oasis",
    album: "Morning Glory?",
    duration: 258,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic Indie Rock",
    description: "The ultimate acoustic rock sing-along classic.",
    isYoutube: true,
    youtubeId: "bx1Bh8Sg370"
  },
  {
    id: "local-train-dil-mere",
    title: "Dil Mere",
    artist: "The Local Train",
    album: "Aalas Ka Pedh",
    duration: 242,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic Indie Rock",
    description: "Reflective ballad carrying nostalgic keyboards.",
    isYoutube: true,
    youtubeId: "r3unEWe4p60"
  },
  {
    id: "dream-note-waqt-ki-baatein",
    title: "Waqt Ki Baatein",
    artist: "Dream Note",
    album: "Single Releases",
    duration: 236,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic Indie Rock",
    description: "Ethereal classical rock fusion exploring passage of time.",
    isYoutube: true,
    youtubeId: "b8gPFS60_1A"
  },
  {
    id: "radiohead-creep",
    title: "Creep",
    artist: "Radiohead",
    album: "Pablo Honey",
    duration: 236,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic Indie Rock",
    description: "Vulnerable alt-rock masterpiece with heavy guitar interventions.",
    isYoutube: true,
    youtubeId: "XFkzRN_HPXU"
  },
  {
    id: "prateek-kuhad-kadam",
    title: "Kadam",
    artist: "Prateek Kuhad",
    album: "Karwaan",
    duration: 202,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic Indie Rock",
    description: "Road-trip acoustic favorite filled with optimism.",
    isYoutube: true,
    youtubeId: "49g_E_KPKD0"
  },
  {
    id: "ritviz-jeet",
    title: "Jeet",
    artist: "Ritviz",
    album: "Jeet EP",
    duration: 238,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Acoustic Indie Rock",
    description: "Hindustani vocals layered with custom analog rock synth kicks.",
    isYoutube: true,
    youtubeId: "YvP6O0g78Yo"
  },

  // 5. Dance
  {
    id: "dj-snake-let-me-love-you",
    title: "Let Me Love You",
    artist: "DJ Snake (ft. Justin Bieber)",
    album: "Encore",
    duration: 205,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Dance",
    description: "Bouncy basslines met with Bieber's sweetest vocals.",
    isYoutube: true,
    youtubeId: "euCqAq60a1Q"
  },
  {
    id: "avicii-wake-me-up",
    title: "Wake Me Up",
    artist: "Avicii",
    album: "True",
    duration: 247,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Dance",
    description: "Acoustic guitar meets high-flying Swedish EDM leads.",
    isYoutube: true,
    youtubeId: "IcrbM1l_BoI"
  },
  {
    id: "swedish-house-mafia-dont-you-worry",
    title: "Don't You Worry Child",
    artist: "Swedish House Mafia",
    album: "Until Now",
    duration: 332,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Dance",
    description: "Epic emotional progressive house classic.",
    isYoutube: true,
    youtubeId: "1y6smkh6cWY"
  },
  {
    id: "david-guetta-titanium",
    title: "Titanium",
    artist: "David Guetta ft. Sia",
    album: "Nothing but the Beat",
    duration: 245,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Dance",
    description: "Powerhouse lyrics met with brilliant synthesizer setups.",
    isYoutube: true,
    youtubeId: "JRfuAAtBFy8"
  },
  {
    id: "major-lazer-lean-on",
    title: "Lean On",
    artist: "Major Lazer & DJ Snake",
    album: "Peace Is the Mission",
    duration: 176,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Dance",
    description: "Globally loved summer dance classic incorporating Eastern soundscapes.",
    isYoutube: true,
    youtubeId: "YqeW9_5kURI"
  },
  {
    id: "alan-walker-faded",
    title: "Faded",
    artist: "Alan Walker",
    album: "Different World",
    duration: 212,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Dance",
    description: "Atmospheric, vocal-heavy melancholic EDM classic.",
    isYoutube: true,
    youtubeId: "60ItHLz5WeA"
  },
  {
    id: "the-chainsmokers-closer",
    title: "Closer",
    artist: "The Chainsmokers ft. Halsey",
    album: "Collage",
    duration: 244,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Dance",
    description: "High-flying commercial electronic pop duet.",
    isYoutube: true,
    youtubeId: "0zGcUoRlhmw"
  },
  {
    id: "martin-garrix-animals",
    title: "Animals",
    artist: "Martin Garrix",
    album: "Gold Skies",
    duration: 304,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Dance",
    description: "Relentless big room house drop driven by woodblocks.",
    isYoutube: true,
    youtubeId: "gCYcHz2k5lo"
  },
  {
    id: "calvin-harris-summer",
    title: "Summer",
    artist: "Calvin Harris",
    album: "Motion",
    duration: 224,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Dance",
    description: "Sun-drenched dynamic summer EDM release.",
    isYoutube: true,
    youtubeId: "ebXbLfLACGM"
  },
  {
    id: "calvin-harris-one-kiss",
    title: "One Kiss",
    artist: "Calvin Harris & Dua Lipa",
    album: "One Kiss Single",
    duration: 214,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Dance",
    description: "Deep house classic utilizing beautiful horn arrangements.",
    isYoutube: true,
    youtubeId: "DkeiKbqa02g"
  },

  // 6. Techno
  {
    id: "charlotte-de-witte-interstellar",
    title: "Interstellar Theme (Techno Edit)",
    artist: "Charlotte de Witte",
    album: "Liquid Sets",
    duration: 350,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Techno",
    description: "Mindbending high-tempo techno adaption of Zimmer's masterpiece.",
    isYoutube: true,
    youtubeId: "J8-p77O97K0"
  },
  {
    id: "darude-sandstorm",
    title: "Sandstorm",
    artist: "Darude",
    album: "Before the Storm",
    duration: 225,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Techno",
    description: "The classic high speed peak adrenaline techno track.",
    isYoutube: true,
    youtubeId: "y6120QOlsfU"
  },
  {
    id: "tiesto-adagio-for-strings",
    title: "Adagio for Strings",
    artist: "Tiësto",
    album: "Parade",
    duration: 440,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Techno",
    description: "Dramatic symphonic peak converted to house music.",
    isYoutube: true,
    youtubeId: "8tIgN7eC594"
  },
  {
    id: "daft-punk-doin-it-right",
    title: "Doin' It Right",
    artist: "Daft Punk ft. Panda Bear",
    album: "Random Access Memories",
    duration: 251,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Techno",
    description: "Analog vocoders paired perfectly with robust modular kicks.",
    isYoutube: true,
    youtubeId: "LL-gyhCVYKI"
  },
  {
    id: "daft-punk-one-more-time",
    title: "One More Time",
    artist: "Daft Punk",
    album: "Discovery",
    duration: 320,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Techno",
    description: "High energy brass filtering loops.",
    isYoutube: true,
    youtubeId: "FGBhQbmPwDK"
  },
  {
    id: "deadmau5-strobe",
    title: "Strobe",
    artist: "deadmau5",
    album: "For Lack of a Better Name",
    duration: 380,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Techno",
    description: "Legendary melodic build that reaches peak electronic heights.",
    isYoutube: true,
    youtubeId: "tKi9Z-f6qX4"
  },
  {
    id: "diplo-on-my-mind",
    title: "On My Mind",
    artist: "Diplo & SIDEPIECE",
    album: "On My Mind Single",
    duration: 181,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Techno",
    description: "Bouncy baseline loops styled for warehouse dances.",
    isYoutube: true,
    youtubeId: "0hDK5YF9oK0"
  },
  {
    id: "fisher-losing-it",
    title: "Losing It",
    artist: "FISHER",
    album: "Losing It",
    duration: 248,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Techno",
    description: "Massive foghorn drops driving minimalist electronic floors.",
    isYoutube: true,
    youtubeId: "h8IDy9G68K0"
  },
  {
    id: "eric-prydz-opus",
    title: "Opus",
    artist: "Eric Prydz",
    album: "Opus",
    duration: 543,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Techno",
    description: "Hypnotic arpeggiators shifting slowly to high velocities.",
    isYoutube: true,
    youtubeId: "iRA8CD-Yo80"
  },
  {
    id: "prodigy-breathe",
    title: "Breathe",
    artist: "The Prodigy",
    album: "The Fat of the Land",
    duration: 239,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Techno",
    description: "High-octane industrial synthesis with aggressive beats.",
    isYoutube: true,
    youtubeId: "r3_h_N_H_Yo"
  },

  // 7. Rock
  {
    id: "the-antigravs-sunrise-live",
    title: "Live Stage: Sunrise",
    artist: "The Antigravs",
    album: "Festival Anthems",
    duration: 198,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Rock",
    description: "Immersive live capture presenting genuine festival feedback.",
    isYoutube: true,
    youtubeId: "Y6-P_jg_PDo"
  },
  {
    id: "eagles-hotel-california",
    title: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
    duration: 390,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Rock",
    description: "The twin guitar classic describing California desert structures.",
    isYoutube: true,
    youtubeId: "098Y_7_97Yo"
  },
  {
    id: "queen-bohemian-rhapsody",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    duration: 355,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Rock",
    description: "Operatic rock piece structured into multiple distinct melodies.",
    isYoutube: true,
    youtubeId: "fJ9rUzIMcZQ"
  },
  {
    id: "guns-n-roses-sweet-child-o-mine",
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    album: "Appetite for Destruction",
    duration: 356,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Rock",
    description: "The highly memorable melodic opener and high range grit vocals.",
    isYoutube: true,
    youtubeId: "1w7OgIMMRc4"
  },
  {
    id: "linkin-park-numb",
    title: "Numb",
    artist: "Linkin Park",
    album: "Meteora",
    duration: 187,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Rock",
    description: "Heavy distorted keyboards backing powerful vocal declarations.",
    isYoutube: true,
    youtubeId: "kXYiU_JCYtU"
  },
  {
    id: "linkin-park-in-the-end",
    title: "In the End",
    artist: "Linkin Park",
    album: "Hybrid Theory",
    duration: 216,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Rock",
    description: "Atmospheric metal chord progressions creating true tension.",
    isYoutube: true,
    youtubeId: "eVTXPUF4Oz4"
  },
  {
    id: "acdc-thunderstruck",
    title: "Thunderstruck",
    artist: "AC/DC",
    album: "The Razors Edge",
    duration: 292,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Rock",
    description: "Immense tapping riffs driving standard classic rock layers.",
    isYoutube: true,
    youtubeId: "v2AC41KEMzU"
  },
  {
    id: "acdc-back-in-black",
    title: "Back In Black",
    artist: "AC/DC",
    album: "Back in Black",
    duration: 255,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Rock",
    description: "Thumping AC/DC rock comeback with iconic heavy styling.",
    isYoutube: true,
    youtubeId: "pAgnJDJN4VA"
  },
  {
    id: "nirvana-smells-like-teen-spirit",
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    album: "Nevermind",
    duration: 301,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Rock",
    description: "The absolute grunge transition from delicate to massive crunch.",
    isYoutube: true,
    youtubeId: "hTWKbfoikeg"
  },
  {
    id: "led-zeppelin-stairway-to-heaven",
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    album: "Led Zeppelin IV",
    duration: 482,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Rock",
    description: "Acoustic wood recorders turning slowly into the ultimate guitar solo.",
    isYoutube: true,
    youtubeId: "QkF3oxziOn4"
  },

  // 8. Chill
  {
    id: "tape-archive-vintage-mix-chill",
    title: "Vintage Mix",
    artist: "Tape Archive",
    album: "Cassette Memoirs",
    duration: 215,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Chill",
    description: "Vintage tape deck tape crackles and soothing delays.",
    isYoutube: true,
    youtubeId: "H0M_7_D9k7o"
  },
  {
    id: "coldplay-strawberry-swing",
    title: "Strawberry Swing",
    artist: "Coldplay",
    album: "Viva la Vida",
    duration: 249,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Chill",
    description: "Relaxing ambient guitar loops carrying lightweight acoustic elements.",
    isYoutube: true,
    youtubeId: "isPv6M-U960"
  },
  {
    id: "post-malone-sunflower",
    title: "Sunflower",
    artist: "Post Malone & Swae Lee",
    album: "Spider-Man OST",
    duration: 158,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Chill",
    description: "Sweet, bouncy background elements making minds relax entirely.",
    isYoutube: true,
    youtubeId: "ApXoWvdgKuU"
  },
  {
    id: "khalid-location",
    title: "Location",
    artist: "Khalid",
    album: "American Teen",
    duration: 219,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Chill",
    description: "Warm soulful R&B hums over reassuring low frequency baselines.",
    isYoutube: true,
    youtubeId: "76189z_L86Y"
  },
  {
    id: "billie-eilish-ocean-eyes",
    title: "Ocean Eyes",
    artist: "Billie Eilish",
    album: "Don't Smile at Me",
    duration: 200,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Chill",
    description: "Ethereal soothing floating notes backed by lightweight beats.",
    isYoutube: true,
    youtubeId: "ViwtNLUqkMY"
  },
  {
    id: "one-direction-night-changes",
    title: "Night Changes",
    artist: "One Direction",
    album: "Four",
    duration: 226,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500&auto=format&fit=crop&q=60",
    genre: "Chill",
    description: "Nostalgic romantic pop story ideal for easy evening contemplation.",
    isYoutube: true,
    youtubeId: "syFZJR9Mc_U"
  },
  {
    id: "the-neighbourhood-softcore",
    title: "Softcore",
    artist: "The Neighbourhood",
    album: "I Love You.",
    duration: 206,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60",
    genre: "Chill",
    description: "Moody synthesizer layers that keep stress level at lowest point.",
    isYoutube: true,
    youtubeId: "g78Z_90YoPM"
  },
  {
    id: "powfu-death-bed",
    title: "Death Bed",
    artist: "Powfu",
    album: "Some Boring Love Stories",
    duration: 173,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    genre: "Chill",
    description: "Cozy lofi drums backing romantic sweet vocal hooks.",
    isYoutube: true,
    youtubeId: "AL-9P_9X7Yo"
  },
  {
    id: "troye-sivan-youth",
    title: "Youth",
    artist: "Troye Sivan",
    album: "Blue Neighbourhood",
    duration: 185,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60",
    genre: "Chill",
    description: "Warm tropical beats blending with highly positive synthesizers.",
    isYoutube: true,
    youtubeId: "XYA7jZ_f6Yk"
  },
  {
    id: "mac-miller-self-care",
    title: "Self Care",
    artist: "Mac Miller",
    album: "Swimming",
    duration: 340,
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
    genre: "Chill",
    description: "Deep cloud-rap vibe that calms mental workflows immediately.",
    isYoutube: true,
    youtubeId: "SsdfG89O_Yo"
  }
];
