/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Track } from './types';

export const PODCAST_HOSTS = [
  "Joe Rogan",
  "Steven Bartlett",
  "Lex Fridman",
  "Tim Ferriss",
  "Andrew Huberman",
  "Patrick Bet-David",
  "Chris Williamson",
  "Lewis Howes",
  "Rich Roll",
  "Peter Attia",
  "Jordan Peterson",
  "Tom Bilyeu",
  "Gary Vaynerchuk",
  "Ranveer Allahbadia",
  "Raj Shamani",
  "Nikhil Kamath",
  "Prakhar Gupta",
  "Cyrus Broacha",
  "Vinamre Kasanaa",
  "Sandeep Maheshwari",
  "Ankur Warikoo",
  "Gaurav Taneja",
  "Varun Mayya",
  "Deepak Kanakaraju",
  "Aman Gupta"
];

export const TRACKS: Track[] = [
  {
    "id": "the-weeknd-blinding-lights",
    "title": "Blinding Lights",
    "artist": "The Weeknd",
    "album": "After Hours",
    "duration": 200,
    "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    "coverUrl": "https://img.youtube.com/vi/4NRXx6U8ABQ/hqdefault.jpg",
    "genre": "Global Pop / Synth Wave",
    "description": "Sensational upbeat retro-80s soundscape. Globally streamed by over a billion fans.",
    "isYoutube": true,
    "youtubeId": "4NRXx6U8ABQ"
  },
  {
    "id": "ar-rahman-dil-se-re",
    "title": "Dil Se Re",
    "artist": "A.R. Rahman",
    "album": "Dil Se",
    "duration": 404,
    "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    "coverUrl": "https://img.youtube.com/vi/YfdfvS06v6U/hqdefault.jpg",
    "genre": "Bollywood / Ambient Classic",
    "description": "A masterpiece of vocal layers and acoustic perfection composed by legendary A.R. Rahman.",
    "isYoutube": true,
    "youtubeId": "YfdfvS06v6U"
  },
  {
    "id": "charlie-puth-how-long",
    "title": "How Long",
    "artist": "Charlie Puth",
    "album": "Voicenotes",
    "duration": 201,
    "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    "coverUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuBRm4JtmJLq6lj-Hq1JQXSnEV16ZpF8d9jy1pu8VZZDMFq_oldHOckdfwfGLuIz8cpeRRIGN8Sv7BQbQC7hWnOFbmyOe2T0an5hC141_6KKkTnetMGeAc2PO8pCiMKJaKHwHHO8xHqWllbZ59gzl4wuqPnZN9R1s_T_PXJb9IdPMDVJjPVLGJGlENH1mtVRCnSDARIej9SK7u5evV5gW_jYFJu0cOxyKSh3ArjzegGxRd53AZp3WbchEuPiZFDzuOnVC5_GqzOkl4TG",
    "genre": "Pop / Synth Pop",
    "description": "Modern bouncy bassline with rich retro synth textures. Perfect pop crossover."
  },
  {
    "id": "local-train-choo-lo",
    "title": "Choo Lo",
    "artist": "The Local Train",
    "album": "Aalas Ka Pedh",
    "duration": 233,
    "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    "coverUrl": "https://img.youtube.com/vi/qN4ooNx77u0/hqdefault.jpg",
    "genre": "Indie Rock",
    "description": "A heart-wrenching indie rock anthem that matches nostalgic twilight guitar delays.",
    "isYoutube": true,
    "youtubeId": "qN4ooNx77u0"
  },
  {
    "id": "prateek-kuhad-cold-mess",
    "title": "Cold / Mess",
    "artist": "Prateek Kuhad",
    "album": "Cold / Mess EP",
    "duration": 210,
    "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    "coverUrl": "https://img.youtube.com/vi/ISYg_S_HGEg/hqdefault.jpg",
    "genre": "Acoustic / Indie Pop",
    "description": "Beautiful acoustic warmth carrying absolute vocal intimacy. A great track for late nights.",
    "isYoutube": true,
    "youtubeId": "ISYg_S_HGEg"
  },
  {
    "id": "dj-snake-let-me-love-you",
    "title": "Let Me Love You",
    "artist": "DJ Snake (ft. Justin Bieber)",
    "album": "Encore",
    "duration": 205,
    "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    "coverUrl": "https://img.youtube.com/vi/euCqAq60a1Q/hqdefault.jpg",
    "genre": "Dance / Electronic",
    "description": "Energetic electronic beats backing Bieber's sweet vocals. Extremely high playrate.",
    "isYoutube": true,
    "youtubeId": "euCqAq60a1Q"
  },
  {
    "id": "club-life-electronic",
    "title": "Club Life: Electronic",
    "artist": "DJ Phantom",
    "album": "Underground Sets",
    "duration": 165,
    "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    "coverUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuDfng9H3Omj9_9RwzWsZKHBAY2Sc6Jz5JsYq7WNUr5_RdN6_iX5wjkZ_l1Ln4PZ_Ifw5Z9O2vhgrKXrRQ04vQs9zCQNv3jjJ7PJikT6qKe2e6ZQ93xyLt441-q0kvF64q_x5IecQCVfN7GvFgVTmVvSWfuMZJSlQB7Q6g5N3-YEHWmWJhxS5Y56Hi0JsbnMh72BihdDpY61ihW2HfSBVRzdZta_V7W15jBiiStYQ7XKTGg4mC3GjnYPZABlwSjiwkD5cY1gVMwPRL0a",
    "genre": "Techno",
    "description": "Energetic underground club mix featuring laser synth leads and thumping house kicks.",
    "isDemo": true
  },
  {
    "id": "space-station-deep-house",
    "title": "Space Station",
    "artist": "Lumina Orbit",
    "album": "Deep House Chronicles",
    "duration": 184,
    "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    "coverUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuAhVsz28PLP3gRG4ydtO2HN2A53Q_J9uS4qqXIK8e-JFoRVUmbhEmARUxkssJ-G6uqB9uuwGvUX93jlC_GcKGPXyhsA4UHBWAujXzvMqWMDexKxj84RncyUxGRznd38exXttWeqg7JjhEctSFi__BVhj6OzrykUqIi_F9AwTNcnFvsp4NrsLxOCgPRBiQ1s1G9egM5fFfKiYcxaUpBK0aZW2N8xRbNksHPmd-I9lVleUJ9qBBntce82tt5--s_AbYSfsXviUTLLOB-E",
    "genre": "Dance",
    "description": "Deep spatial atmosphere sound waves with a warm, driving low-end pulse.",
    "isDemo": true
  },
  {
    "id": "retro-vintage-mix",
    "title": "Vintage Mix",
    "artist": "Tape Archive",
    "album": "Cassette Memoirs",
    "duration": 215,
    "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    "coverUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuCByaUJCAscYqf8Hbzvkk_RZJkJ9DYzRXwczG96jEa2meqiEtqqSixKc4boWvqcf-QDvtOR3wQgEoqBtmjIO4ZqHcehVYD0tZ1PNmwGuZEA0qNZ4wNO424ISrNlkDBTCBu0uXXtc_sSkXh-7v6sYRX6dJg5PYRoce5ie1QZD2ZRoco2F8hmE0XftRlL1HfA5OS4yCOzsiHtT29gtU3No4gmWJMZ869xxUIzhCOFJNu-Qt2RCv7IPrXvmlSU3cuFzKF1vicOAiMdbZk0",
    "genre": "Chill",
    "description": "Moody lofi tape aesthetic with nostalgic vinyl crackling, tape hiss, and guitar delay.",
    "isDemo": true
  },
  {
    "id": "live-ocean-stage",
    "title": "Live Stage: Sunrise",
    "artist": "The Antigravs",
    "album": "Festival Anthems",
    "duration": 198,
    "url": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    "coverUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuBqDG2vWARJJC5zcEoAOkEZhvMKKyrZcx_EHANUSnUBO2OrtwpqmFysuLZ3MgMZK1KIF0HcKE7dBk6iRlFObzMq1a4l9K9qdej-I8UT0Di5PQrLxcC5CZlfxu56qPRNSJV7WtezkWvJOXOHbGeIpB9CVmkh4rituGG8UnsH3w6pxAQhs-nUEOjc-iNeTMXv2dpcQVO27c7d6YKULpJsm5uwao7FMuk6rPfb-uNo6IR2fgwe8r1k1vVWDiIIAv0jzcbafgpttYZPUlgp",
    "genre": "Rock",
    "description": "Immersive live performance capture detailing real crowd ambience and roaring feedback.",
    "isDemo": true
  },
  {
    "id": "yt-podcast-IYWbbxdfGvc",
    "title": "Business Expert: How to Build A Brand in 2026 & Hidden Opportunity | IndiaMART | FO443 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Business & Entrepreneurship",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=IYWbbxdfGvc",
    "coverUrl": "https://i.ytimg.com/vi/IYWbbxdfGvc/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Download Porter Here: https://app.adjust.com/1vq8o2nq -------------- Guest Suggestion Form: ...",
    "isYoutube": true,
    "youtubeId": "IYWbbxdfGvc",
    "isPodcast": true,
    "category": "Business & Entrepreneurship"
  },
  {
    "id": "yt-podcast-JABjvOCl4Mg",
    "title": "How To Start A Business With 25K? Ideas, Plan & Marketing | Shiprocket Founder | FO285 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Business & Entrepreneurship",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=JABjvOCl4Mg",
    "coverUrl": "https://i.ytimg.com/vi/JABjvOCl4Mg/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Use The Websites To Grow Your Business: Niche Scraper: https://nichescraper.com/ Exploding Topics: ...",
    "isYoutube": true,
    "youtubeId": "JABjvOCl4Mg",
    "isPodcast": true,
    "category": "Business & Entrepreneurship"
  },
  {
    "id": "yt-podcast-xAt1xcC6qfM",
    "title": "Bill Gates on India, Billion-Dollar Business Opportunities, PM Modi & Children | FO335 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Business & Entrepreneurship",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=xAt1xcC6qfM",
    "coverUrl": "https://i.ytimg.com/vi/xAt1xcC6qfM/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Visit Website: https://www.gatesfoundation.org/ -------------- Guest Suggestion Form: https://forms.gle/bnaeY3FpoFU9ZjA47 ...",
    "isYoutube": true,
    "youtubeId": "xAt1xcC6qfM",
    "isPodcast": true,
    "category": "Business & Entrepreneurship"
  },
  {
    "id": "yt-podcast-m1DQx1_mweE",
    "title": "Start Business With No Money In India & Business Secrets - Rajiv Talreja | FO368 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Business & Entrepreneurship",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=m1DQx1_mweE",
    "coverUrl": "https://i.ytimg.com/vi/m1DQx1_mweE/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Grow Your Business: https://swiy.co/BSW-RSP -------------- Guest Suggestion Form: https://forms.gle/bnaeY3FpoFU9ZjA47 ...",
    "isYoutube": true,
    "youtubeId": "m1DQx1_mweE",
    "isPodcast": true,
    "category": "Business & Entrepreneurship"
  },
  {
    "id": "yt-podcast-kxLmeUIXXtU",
    "title": "Entrepreneurship Expert: How To Build A $1m Business Without Hard Work!",
    "artist": "The Diary Of A CEO",
    "album": "Business & Entrepreneurship",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=kxLmeUIXXtU",
    "coverUrl": "https://i.ytimg.com/vi/kxLmeUIXXtU/hqdefault.jpg",
    "genre": "Podcast",
    "description": "This episode will teach you everything you would learn in a business degree, saving you $200000 and 10000 hours Josh ...",
    "isYoutube": true,
    "youtubeId": "kxLmeUIXXtU",
    "isPodcast": true,
    "category": "Business & Entrepreneurship"
  },
  {
    "id": "yt-podcast-uKQIRFr0oYg",
    "title": "🔥🔥99TH SPECIAL ON RAW TALKS | ZOHO STORY | Ft. RAJU VEGESNA | Telugu Podcast | Raw Talks With VK |",
    "artist": "Raw Talks With VK",
    "album": "Business & Entrepreneurship",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=uKQIRFr0oYg",
    "coverUrl": "https://i.ytimg.com/vi/uKQIRFr0oYg/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Zoho workplace: https://youtube.com/@ZohoWorkplace?si=SDUvoQkCb0Yyt4lb Mr. Raju Vegesna – Chief Evangelist at Zoho ...",
    "isYoutube": true,
    "youtubeId": "uKQIRFr0oYg",
    "isPodcast": true,
    "category": "Business & Entrepreneurship"
  },
  {
    "id": "yt-podcast-YIszsqhLGIs",
    "title": "Why the Rich Think Differently: Millionaire Mindset & Wealth Secrets - Kunal Shah |FO389 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Business & Entrepreneurship",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=YIszsqhLGIs",
    "coverUrl": "https://i.ytimg.com/vi/YIszsqhLGIs/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Download Porter Here: https://app.adjust.com/1ruavzu2 T&C Apply -------------- Guest Suggestion Form: ...",
    "isYoutube": true,
    "youtubeId": "YIszsqhLGIs",
    "isPodcast": true,
    "category": "Business & Entrepreneurship"
  },
  {
    "id": "yt-podcast-Lj10t7OkYN8",
    "title": "🤯🤯 Pent House Nundi 8k Crores Startup|Telugu Business Podcast| RawTalks withVK Ep-61",
    "artist": "Raw Talks With VK",
    "album": "Business & Entrepreneurship",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=Lj10t7OkYN8",
    "coverUrl": "https://i.ytimg.com/vi/Lj10t7OkYN8/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Disclaimer: This video is for educational purposes only. The opinions expressed by the guests are their personal views and do not ...",
    "isYoutube": true,
    "youtubeId": "Lj10t7OkYN8",
    "isPodcast": true,
    "category": "Business & Entrepreneurship"
  },
  {
    "id": "yt-podcast-aGU7gropbwU",
    "title": "How to Start a Successful Startup in India | Real Reasons Why Startups Fail - Complete Guide EP 1",
    "artist": "Vidvika Growth Talks",
    "album": "Business & Entrepreneurship",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=aGU7gropbwU",
    "coverUrl": "https://i.ytimg.com/vi/aGU7gropbwU/hqdefault.jpg",
    "genre": "Podcast",
    "description": "MY NEW CHANNEL LINK: https://www.youtube.com/@SriLakshmiIyengar In this episode of Vidvika Growth Talks, we discuss how ...",
    "isYoutube": true,
    "youtubeId": "aGU7gropbwU",
    "isPodcast": true,
    "category": "Business & Entrepreneurship"
  },
  {
    "id": "yt-podcast-zZ-VeqYPxoA",
    "title": "Dr. Velumani On Building ₹5000 Crore Business, Poverty, Risk & Success | FO174 | Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Business & Entrepreneurship",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=zZ-VeqYPxoA",
    "coverUrl": "https://i.ytimg.com/vi/zZ-VeqYPxoA/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Guest Suggestion Form: https://forms.gle/bnaeY3FpoFU9ZjA47 -------------- Dr Velumani's Email Id: focus.velu@gmail.com ...",
    "isYoutube": true,
    "youtubeId": "zZ-VeqYPxoA",
    "isPodcast": true,
    "category": "Business & Entrepreneurship"
  },
  {
    "id": "yt-podcast-0-FUhQKe-eU",
    "title": "Start Earning Money With AI - Free Tools & Business Ideas | Vaibhav Sisinty | FO376 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Technology & AI",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=0-FUhQKe-eU",
    "coverUrl": "https://i.ytimg.com/vi/0-FUhQKe-eU/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Check out this Roadmap to become an AI Generalist: https://link.growthschool.io/Rajshamanii Join this Exclusive WhatsApp ...",
    "isYoutube": true,
    "youtubeId": "0-FUhQKe-eU",
    "isPodcast": true,
    "category": "Technology & AI"
  },
  {
    "id": "yt-podcast-RMAux-sD1bA",
    "title": "Smartest Way To Use AI: Powerful Words, Tools & Next Revolution | Sowmay Jain | FO439 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Technology & AI",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=RMAux-sD1bA",
    "coverUrl": "https://i.ytimg.com/vi/RMAux-sD1bA/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Bhindi AI: https://bhindi.io/ -------------- Guest Suggestion Form: https://forms.gle/bnaeY3FpoFU9ZjA47 -------------- Disclaimer: This ...",
    "isYoutube": true,
    "youtubeId": "RMAux-sD1bA",
    "isPodcast": true,
    "category": "Technology & AI"
  },
  {
    "id": "yt-podcast-5ZYEq6-5RwI",
    "title": "Quantum AI Can Destroy Humanity, Hack Everything, End Every Encryption? | Amit Dubey Podcast",
    "artist": "Switch",
    "album": "Technology & AI",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=5ZYEq6-5RwI",
    "coverUrl": "https://i.ytimg.com/vi/5ZYEq6-5RwI/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Quantum AI is a technology that could be the biggest blessing or the biggest curse for humanity. In this podcast, I sit down with ...",
    "isYoutube": true,
    "youtubeId": "5ZYEq6-5RwI",
    "isPodcast": true,
    "category": "Technology & AI"
  },
  {
    "id": "yt-podcast-OFEY5-52ru0",
    "title": "How AI Will Change Quantum Computing | NVIDIA AI Podcast Ep. 294",
    "artist": "NVIDIA",
    "album": "Technology & AI",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=OFEY5-52ru0",
    "coverUrl": "https://i.ytimg.com/vi/OFEY5-52ru0/hqdefault.jpg",
    "genre": "Podcast",
    "description": "What happens when you combine AI with quantum computing? NVIDIA's Nic Harrigan joins the AI Podcast to break down the ...",
    "isYoutube": true,
    "youtubeId": "OFEY5-52ru0",
    "isPodcast": true,
    "category": "Technology & AI"
  },
  {
    "id": "yt-podcast-NcTcYDjBNNk",
    "title": "Steal this AI Prompt: Business Ideas, Tools & Smart AI Hacks | Vaibhav Sisinty | FO432 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Technology & AI",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=NcTcYDjBNNk",
    "coverUrl": "https://i.ytimg.com/vi/NcTcYDjBNNk/hqdefault.jpg",
    "genre": "Podcast",
    "description": "For links to the prompts and tools, join the WhatsApp community and check the group description: https://figuringoutai.co/ Free ...",
    "isYoutube": true,
    "youtubeId": "NcTcYDjBNNk",
    "isPodcast": true,
    "category": "Technology & AI"
  },
  {
    "id": "yt-podcast-7ARBJQn6QkM",
    "title": "NVIDIA CEO Jensen Huang's Vision for the Future",
    "artist": "Cleo Abram",
    "album": "Technology & AI",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=7ARBJQn6QkM",
    "coverUrl": "https://i.ytimg.com/vi/7ARBJQn6QkM/hqdefault.jpg",
    "genre": "Podcast",
    "description": "What NVIDIA is trying to build next… Subscribe for more optimistic science and tech stories from our show Huge If True. You're ...",
    "isYoutube": true,
    "youtubeId": "7ARBJQn6QkM",
    "isPodcast": true,
    "category": "Technology & AI"
  },
  {
    "id": "yt-podcast-UUPiLFA-Og4",
    "title": "‼️⚠️ ASSALU MISS AVVAKANDI | @vaibhavsisinty 1st AI Podcast on Raw Talks | Telugu Podcast Ep - 91",
    "artist": "Raw Talks With VK",
    "album": "Technology & AI",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=UUPiLFA-Og4",
    "coverUrl": "https://i.ytimg.com/vi/UUPiLFA-Og4/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Book your interview slot for the AI Generalist Fellowship here: https://link.outskill.com/AIGF1 Checkout this Roadmap to become ...",
    "isYoutube": true,
    "youtubeId": "UUPiLFA-Og4",
    "isPodcast": true,
    "category": "Technology & AI"
  },
  {
    "id": "yt-podcast-KpOcUrPdx-4",
    "title": "Artificial Intelligence in 2025 | 60 Minutes Full Episodes",
    "artist": "60 Minutes",
    "album": "Technology & AI",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=KpOcUrPdx-4",
    "coverUrl": "https://i.ytimg.com/vi/KpOcUrPdx-4/hqdefault.jpg",
    "genre": "Podcast",
    "description": "From November, Anderson Cooper's report on why Anthropic's CEO spends so much time warning of AI's potential dangers.",
    "isYoutube": true,
    "youtubeId": "KpOcUrPdx-4",
    "isPodcast": true,
    "category": "Technology & AI"
  },
  {
    "id": "yt-podcast-7fsb6ZESyzE",
    "title": "Earn Crores with AI: Business Ideas, Claude, Free Tools & Prompts | Vaibhav | FO499 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Technology & AI",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=7fsb6ZESyzE",
    "coverUrl": "https://i.ytimg.com/vi/7fsb6ZESyzE/hqdefault.jpg",
    "genre": "Podcast",
    "description": "For links to the prompts and tools, join the WhatsApp community: https://figuringoutai.co/ Get your hand-picked playbook here: ...",
    "isYoutube": true,
    "youtubeId": "7fsb6ZESyzE",
    "isPodcast": true,
    "category": "Technology & AI"
  },
  {
    "id": "yt-podcast-keEi0LoZwL0",
    "title": "AI Masterclass: Become an Expert at Claude, Gemini & Powerful AI Tools | Vaibhav | FO480 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Technology & AI",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=keEi0LoZwL0",
    "coverUrl": "https://i.ytimg.com/vi/keEi0LoZwL0/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Business plan tester prompt: https://bit.ly/46R7hup For links to the prompts and tools, join the WhatsApp community & check the ...",
    "isYoutube": true,
    "youtubeId": "keEi0LoZwL0",
    "isPodcast": true,
    "category": "Technology & AI"
  },
  {
    "id": "yt-podcast-PnqJllk3RfA",
    "title": "MONEY EXPERTS: If I Had to Make 1 MILLION From $0 — Here's EXACTLY What I'd Do!",
    "artist": "Jay Shetty Podcast",
    "album": "Finance & Investing",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=PnqJllk3RfA",
    "coverUrl": "https://i.ytimg.com/vi/PnqJllk3RfA/hqdefault.jpg",
    "genre": "Podcast",
    "description": "What does “financial freedom” mean to you? What's one thing you wish you learned about money earlier? In this On Purpose ...",
    "isYoutube": true,
    "youtubeId": "PnqJllk3RfA",
    "isPodcast": true,
    "category": "Finance & Investing"
  },
  {
    "id": "yt-podcast-vdBt0zeRRAY",
    "title": "30 min with $7Bn Fund Manager, 25 Years of Investing Revealed | 1% Club Show Ep 59",
    "artist": "Finance With Sharan",
    "album": "Finance & Investing",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=vdBt0zeRRAY",
    "coverUrl": "https://i.ytimg.com/vi/vdBt0zeRRAY/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Register for my Retire Early Masterclass: https://bit.ly/3YYYd2o Join the 1% Club: https://bit.ly/4lYFG07 Subscribe: 1% Club ...",
    "isYoutube": true,
    "youtubeId": "vdBt0zeRRAY",
    "isPodcast": true,
    "category": "Finance & Investing"
  },
  {
    "id": "yt-podcast-Cda-fUJ-GjE",
    "title": "Investment Hacks, Vacations, Shopping & Personal Finance - Vikas Jain | Multipl | FO 257 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Finance & Investing",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=Cda-fUJ-GjE",
    "coverUrl": "https://i.ytimg.com/vi/Cda-fUJ-GjE/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Check out Multipl - The only app to invest in mutual funds for your spends Testdrive Spendvesting - Get ₹1000 Amazon Shopping ...",
    "isYoutube": true,
    "youtubeId": "Cda-fUJ-GjE",
    "isPodcast": true,
    "category": "Finance & Investing"
  },
  {
    "id": "yt-podcast-HNz2wBxoZ8Y",
    "title": "2026 MONEY EMERGENCY 🚨 - How To Save & Build Smartly l FD, Gold, Stocks & Savings l Sanjay K On TRS",
    "artist": "Ranveer Allahbadia",
    "album": "Finance & Investing",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=HNz2wBxoZ8Y",
    "coverUrl": "https://i.ytimg.com/vi/HNz2wBxoZ8Y/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Explore Our Other Podcasts Featuring Top Financial Experts Below ...",
    "isYoutube": true,
    "youtubeId": "HNz2wBxoZ8Y",
    "isPodcast": true,
    "category": "Finance & Investing"
  },
  {
    "id": "yt-podcast-Ai4iNmW2A1c",
    "title": "The Best Financial Advice You’ll Ever Hear",
    "artist": "Mel Robbins",
    "album": "Finance & Investing",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=Ai4iNmW2A1c",
    "coverUrl": "https://i.ytimg.com/vi/Ai4iNmW2A1c/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Order your copy of The Let Them Theory https://melrob.co/let-them-theory The #1 Best Selling Book of 2025 Discover how ...",
    "isYoutube": true,
    "youtubeId": "Ai4iNmW2A1c",
    "isPodcast": true,
    "category": "Finance & Investing"
  },
  {
    "id": "yt-podcast-cpg78ouK54I",
    "title": "Dropout To Billionaire - Zerodha's Founder Nikhil Kamath's Journey To SUCCESS - FO5| Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Finance & Investing",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=cpg78ouK54I",
    "coverUrl": "https://i.ytimg.com/vi/cpg78ouK54I/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Order my first book 'Build, Don't Talk' here: https://amzn.eu/d/eCfijRu --------------- Smell good, feel confident. Use my code Raj10 to ...",
    "isYoutube": true,
    "youtubeId": "cpg78ouK54I",
    "isPodcast": true,
    "category": "Finance & Investing"
  },
  {
    "id": "yt-podcast-V360AygOv7A",
    "title": "Financial Literacy for Dummies (Like Me) with JL Collins",
    "artist": "Hasan Minhaj",
    "album": "Finance & Investing",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=V360AygOv7A",
    "coverUrl": "https://i.ytimg.com/vi/V360AygOv7A/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Hasan sits down with personal finance guru JL Collins to talk about his book “The Simple Path To Wealth,” why so many people ...",
    "isYoutube": true,
    "youtubeId": "V360AygOv7A",
    "isPodcast": true,
    "category": "Finance & Investing"
  },
  {
    "id": "yt-podcast-Aog5U44xnKQ",
    "title": "Investing Like a Millionaire | Dave Ramsey's Greatest Hits",
    "artist": "The Ramsey Show Highlights",
    "album": "Finance & Investing",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=Aog5U44xnKQ",
    "coverUrl": "https://i.ytimg.com/vi/Aog5U44xnKQ/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Start eliminating debt for free with EveryDollar - https://ter.li/3w6nto Have a question for the show? Call 888-825-5225 ...",
    "isYoutube": true,
    "youtubeId": "Aog5U44xnKQ",
    "isPodcast": true,
    "category": "Finance & Investing"
  },
  {
    "id": "yt-podcast-66CibydGEJA",
    "title": "Stock Market, Money Making Secrets, Investment & Rich Life - Dinesh Thakkar | FO202 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Finance & Investing",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=66CibydGEJA",
    "coverUrl": "https://i.ytimg.com/vi/66CibydGEJA/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Order 'Build, Don't Talk' (in English) here: https://amzn.eu/d/eCfijRu Order 'Build Don't Talk' (in Hindi) here: ...",
    "isYoutube": true,
    "youtubeId": "66CibydGEJA",
    "isPodcast": true,
    "category": "Finance & Investing"
  },
  {
    "id": "yt-podcast-0YKTsHr5bDE",
    "title": "WTF Is Wealth? Ray Dalio Breaks It Down w/ Nikhil Kamath | WTF is Finance Ep 2",
    "artist": "Nikhil Kamath",
    "album": "Finance & Investing",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=0YKTsHr5bDE",
    "coverUrl": "https://i.ytimg.com/vi/0YKTsHr5bDE/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Wealth can be created easily — but that doesn't mean it's real. In WTF is Finance, Ray Dalio explains how money actually works, ...",
    "isYoutube": true,
    "youtubeId": "0YKTsHr5bDE",
    "isPodcast": true,
    "category": "Finance & Investing"
  },
  {
    "id": "yt-podcast-_l4xZLssfUY",
    "title": "How to Be Consistent: A Simple Secret to Personal Development",
    "artist": "The Mindset Mentor Podcast",
    "album": "Self-Improvement",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=_l4xZLssfUY",
    "coverUrl": "https://i.ytimg.com/vi/_l4xZLssfUY/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Freedom Live is a 3-day live experience in Austin for high performers ready to break through the patterns, beliefs, and identity ...",
    "isYoutube": true,
    "youtubeId": "_l4xZLssfUY",
    "isPodcast": true,
    "category": "Self-Improvement"
  },
  {
    "id": "yt-podcast-k7ChMqZUa5s",
    "title": "Give yourself permission to LEARN. #selfimprovement #motivation #podcast",
    "artist": "Jay Shetty Podcast",
    "album": "Self-Improvement",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=k7ChMqZUa5s",
    "coverUrl": "https://i.ytimg.com/vi/k7ChMqZUa5s/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Give yourself permission to LEARN. #selfimprovement #motivation #podcast.",
    "isYoutube": true,
    "youtubeId": "k7ChMqZUa5s",
    "isPodcast": true,
    "category": "Self-Improvement"
  },
  {
    "id": "yt-podcast-d7sUWwHugg8",
    "title": "Joe Dispenza: You've Been Programmed To Stay BROKE, STUCK & EXHAUSTED - Here's How To Break It!",
    "artist": "Jay Shetty Podcast",
    "album": "Self-Improvement",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=d7sUWwHugg8",
    "coverUrl": "https://i.ytimg.com/vi/d7sUWwHugg8/hqdefault.jpg",
    "genre": "Podcast",
    "description": "If you like this episode, you'll also enjoy my podcast with @DrDanielAmen_BrainHealth Check it out right here ...",
    "isYoutube": true,
    "youtubeId": "d7sUWwHugg8",
    "isPodcast": true,
    "category": "Self-Improvement"
  },
  {
    "id": "yt-podcast-L5Nb1MTHxUI",
    "title": "10 Habits for Self Improvement (Life Changing & Motivating)",
    "artist": "The Balance Theory Podcast",
    "album": "Self-Improvement",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=L5Nb1MTHxUI",
    "coverUrl": "https://i.ytimg.com/vi/L5Nb1MTHxUI/hqdefault.jpg",
    "genre": "Podcast",
    "description": "If you are someone who is on a journey like me where you are getting curious about yourself, want to improve your life, are ...",
    "isYoutube": true,
    "youtubeId": "L5Nb1MTHxUI",
    "isPodcast": true,
    "category": "Self-Improvement"
  },
  {
    "id": "yt-podcast-nsFUKWBQUtI",
    "title": "🔥🔥SAVE THIS! This will push you to move | Yint Money | Ep #37",
    "artist": "Yint Money",
    "album": "Self-Improvement",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=nsFUKWBQUtI",
    "coverUrl": "https://i.ytimg.com/vi/nsFUKWBQUtI/hqdefault.jpg",
    "genre": "Podcast",
    "description": "In this powerful episode of our Telugu podcast, we sit down with Indivar Reddy, a leading fitness Expert and Mentor, to explore ...",
    "isYoutube": true,
    "youtubeId": "nsFUKWBQUtI",
    "isPodcast": true,
    "category": "Self-Improvement"
  },
  {
    "id": "yt-podcast-HRqbzmCjCZE",
    "title": "Podcasts to listen to for personal growth and self-improvement #podcastrecommendations #selfgrowth",
    "artist": "Monica Villegas",
    "album": "Self-Improvement",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=HRqbzmCjCZE",
    "coverUrl": "https://i.ytimg.com/vi/HRqbzmCjCZE/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Highly engaging Self-Improvement discussion.",
    "isYoutube": true,
    "youtubeId": "HRqbzmCjCZE",
    "isPodcast": true,
    "category": "Self-Improvement"
  },
  {
    "id": "yt-podcast-SwQhKFMxmDY",
    "title": "Change Your Brain: Neuroscientist Dr. Andrew Huberman | Rich Roll Podcast",
    "artist": "Rich Roll",
    "album": "Self-Improvement",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=SwQhKFMxmDY",
    "coverUrl": "https://i.ytimg.com/vi/SwQhKFMxmDY/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Thanks for watching! Read all about Dr. Andrew Huberman here https://bit.ly/richroll533 Dr. Andrew Huberman is a ...",
    "isYoutube": true,
    "youtubeId": "SwQhKFMxmDY",
    "isPodcast": true,
    "category": "Self-Improvement"
  },
  {
    "id": "yt-podcast-hcvmq-hcDIE",
    "title": "Top 10 Rules To Win In 2025, Develop A Winner Mindset & Change Your Life | FO297 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Self-Improvement",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=hcvmq-hcDIE",
    "coverUrl": "https://i.ytimg.com/vi/hcvmq-hcDIE/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Guest Suggestion Form: https://forms.gle/bnaeY3FpoFU9ZjA47 -------------- Disclaimer: This video is intended solely for ...",
    "isYoutube": true,
    "youtubeId": "hcvmq-hcDIE",
    "isPodcast": true,
    "category": "Self-Improvement"
  },
  {
    "id": "yt-podcast-ufQEqi4LUZ4",
    "title": "Mindset Reset: Take Control of Your Mental Habits | The Mel Robbins Podcast",
    "artist": "Mel Robbins",
    "album": "Self-Improvement",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=ufQEqi4LUZ4",
    "coverUrl": "https://i.ytimg.com/vi/ufQEqi4LUZ4/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Order your copy of The Let Them Theory https://melrob.co/let-them-theory The #1 Best Selling Book of 2025 Discover how ...",
    "isYoutube": true,
    "youtubeId": "ufQEqi4LUZ4",
    "isPodcast": true,
    "category": "Self-Improvement"
  },
  {
    "id": "yt-podcast-U_xf1_PWgjE",
    "title": "Raj Shamani's brain test 😱 #braintest #rajshamani #mindset #motivation #podcast",
    "artist": "Ajay Inspiration",
    "album": "Self-Improvement",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=U_xf1_PWgjE",
    "coverUrl": "https://i.ytimg.com/vi/U_xf1_PWgjE/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Raj Shamani's brain test #braintest #rajshamani #mindset #motivation #podcast.",
    "isYoutube": true,
    "youtubeId": "U_xf1_PWgjE",
    "isPodcast": true,
    "category": "Self-Improvement"
  },
  {
    "id": "yt-podcast-xi-zHJL5bnI",
    "title": "Diet Expert: Weight Loss, Calories, Digestion, Sugar & Belly Fat | Pooja Makhija | FO433 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Health & Fitness",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=xi-zHJL5bnI",
    "coverUrl": "https://i.ytimg.com/vi/xi-zHJL5bnI/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Guest Suggestion Form: https://forms.gle/bnaeY3FpoFU9ZjA47 -------------- Trying to grow your Social Media? Talk to us- ...",
    "isYoutube": true,
    "youtubeId": "xi-zHJL5bnI",
    "isPodcast": true,
    "category": "Health & Fitness"
  },
  {
    "id": "yt-podcast-altjt8zrCLc",
    "title": "How To Stay Healthy & Fit Even If You Have No Time",
    "artist": "Dr Pal",
    "album": "Health & Fitness",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=altjt8zrCLc",
    "coverUrl": "https://i.ytimg.com/vi/altjt8zrCLc/hqdefault.jpg",
    "genre": "Podcast",
    "description": "In this episode, I sit down with Dr Sheela Nambiar to break down everything people are confused about when it comes to exercise ...",
    "isYoutube": true,
    "youtubeId": "altjt8zrCLc",
    "isPodcast": true,
    "category": "Health & Fitness"
  },
  {
    "id": "yt-podcast--Kd7I6GrdGM",
    "title": "8 Realistic Healthy Habits That Make a Huge Difference",
    "artist": "Mel Robbins",
    "album": "Health & Fitness",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=-Kd7I6GrdGM",
    "coverUrl": "https://i.ytimg.com/vi/-Kd7I6GrdGM/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Order your copy of The Let Them Theory https://melrob.co/let-them-theory The #1 Best Selling Book of 2025 Discover how ...",
    "isYoutube": true,
    "youtubeId": "-Kd7I6GrdGM",
    "isPodcast": true,
    "category": "Health & Fitness"
  },
  {
    "id": "yt-podcast-mMHNvy9pFj0",
    "title": "Change Your Body & Your Life in 1 Month: 4 Small Habits That Actually Work",
    "artist": "Mel Robbins",
    "album": "Health & Fitness",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=mMHNvy9pFj0",
    "coverUrl": "https://i.ytimg.com/vi/mMHNvy9pFj0/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Order your copy of The Let Them Theory https://melrob.co/let-them-theory The #1 Best Selling Book of 2025 Discover how ...",
    "isYoutube": true,
    "youtubeId": "mMHNvy9pFj0",
    "isPodcast": true,
    "category": "Health & Fitness"
  },
  {
    "id": "yt-podcast-h_1zlead9ZU",
    "title": "How to Lose Fat & Gain Muscle With Nutrition | Alan Aragon",
    "artist": "Andrew Huberman",
    "album": "Health & Fitness",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=h_1zlead9ZU",
    "coverUrl": "https://i.ytimg.com/vi/h_1zlead9ZU/hqdefault.jpg",
    "genre": "Podcast",
    "description": "My guest is Alan Aragon, a renowned nutrition and fitness expert and researcher known for sharing the strongest evidence-based ...",
    "isYoutube": true,
    "youtubeId": "h_1zlead9ZU",
    "isPodcast": true,
    "category": "Health & Fitness"
  },
  {
    "id": "yt-podcast-cEVAjm_ETtY",
    "title": "The Body Reset: How Women Should Eat & Exercise for Health, Fat Loss, & Energy | Dr. Stacy Sims",
    "artist": "Mel Robbins",
    "album": "Health & Fitness",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=cEVAjm_ETtY",
    "coverUrl": "https://i.ytimg.com/vi/cEVAjm_ETtY/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Order your copy of The Let Them Theory https://melrob.co/let-them-theory The #1 Best Selling Book of 2025 Discover how ...",
    "isYoutube": true,
    "youtubeId": "cEVAjm_ETtY",
    "isPodcast": true,
    "category": "Health & Fitness"
  },
  {
    "id": "yt-podcast-jtgxSDACnyU",
    "title": "Live 10 Years Longer: Brain & Heart Health, Workouts & Fitness Business | Gabit | FO357 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Health & Fitness",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=jtgxSDACnyU",
    "coverUrl": "https://i.ytimg.com/vi/jtgxSDACnyU/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Visit Website: www.gabit.com/ring -------------- Guest Suggestion Form: https://forms.gle/bnaeY3FpoFU9ZjA47 ...",
    "isYoutube": true,
    "youtubeId": "jtgxSDACnyU",
    "isPodcast": true,
    "category": "Health & Fitness"
  },
  {
    "id": "yt-podcast-yNbyUd2alyA",
    "title": "Mental-Physical Fitness 1O1 - Mentality Training With Saket Gokhale & Ranveer Allahbadia | TRS",
    "artist": "Ranveer Allahbadia",
    "album": "Health & Fitness",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=yNbyUd2alyA",
    "coverUrl": "https://i.ytimg.com/vi/yNbyUd2alyA/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Check out BeerBiceps SkillHouse's Monetizing Content Creation Course- https://bbsh.in/ra-yt-mcc Share your guest suggestions ...",
    "isYoutube": true,
    "youtubeId": "yNbyUd2alyA",
    "isPodcast": true,
    "category": "Health & Fitness"
  },
  {
    "id": "yt-podcast-Bk0lQtAcm1I",
    "title": "Beginner to Advanced Gym Guide | GunjanShouts with Yatinder Singh",
    "artist": "GunjanShouts",
    "album": "Health & Fitness",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=Bk0lQtAcm1I",
    "coverUrl": "https://i.ytimg.com/vi/Bk0lQtAcm1I/hqdefault.jpg",
    "genre": "Podcast",
    "description": "How do you go from a complete beginner in the gym to building a strong, aesthetic physique naturally? In this powerful episode of ...",
    "isYoutube": true,
    "youtubeId": "Bk0lQtAcm1I",
    "isPodcast": true,
    "category": "Health & Fitness"
  },
  {
    "id": "yt-podcast-pZX8ikmWvEU",
    "title": "Female-Specific Exercise & Nutrition for Health, Performance & Longevity | Dr. Stacy Sims",
    "artist": "Andrew Huberman",
    "album": "Health & Fitness",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=pZX8ikmWvEU",
    "coverUrl": "https://i.ytimg.com/vi/pZX8ikmWvEU/hqdefault.jpg",
    "genre": "Podcast",
    "description": "In this episode, my guest is Dr. Stacy Sims, Ph.D., an exercise physiologist, nutrition scientist, and expert in female-specific ...",
    "isYoutube": true,
    "youtubeId": "pZX8ikmWvEU",
    "isPodcast": true,
    "category": "Health & Fitness"
  },
  {
    "id": "yt-podcast-CbLBSY52578",
    "title": "Humanities നിസ്സാരമല്ല, ലക്ഷങ്ങൾ നേടാം | B-Tech, MBBS, Degrees & Opportunities| Masterclass |Podcast",
    "artist": "Pink Podcast",
    "album": "Education",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=CbLBSY52578",
    "coverUrl": "https://i.ytimg.com/vi/CbLBSY52578/hqdefault.jpg",
    "genre": "Podcast",
    "description": "For Career Planning Related Doubts, visit https://tinyurl.com/pinkpodcast ---- For Advertisement and Podcast queries on PINK ...",
    "isYoutube": true,
    "youtubeId": "CbLBSY52578",
    "isPodcast": true,
    "category": "Education"
  },
  {
    "id": "yt-podcast-liyn5xWvx44",
    "title": "Which country has the best education in the world? - The Global Story podcast, BBC World Service",
    "artist": "BBC World Service",
    "album": "Education",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=liyn5xWvx44",
    "coverUrl": "https://i.ytimg.com/vi/liyn5xWvx44/hqdefault.jpg",
    "genre": "Podcast",
    "description": "A good education can help change lives, but some children face huge barriers. Click here to subscribe to our channel ...",
    "isYoutube": true,
    "youtubeId": "liyn5xWvx44",
    "isPodcast": true,
    "category": "Education"
  },
  {
    "id": "yt-podcast-U_xf1_PWgjE",
    "title": "Raj Shamani's brain test 😱 #braintest #rajshamani #mindset #motivation #podcast",
    "artist": "Ajay Inspiration",
    "album": "Education",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=U_xf1_PWgjE",
    "coverUrl": "https://i.ytimg.com/vi/U_xf1_PWgjE/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Raj Shamani's brain test #braintest #rajshamani #mindset #motivation #podcast.",
    "isYoutube": true,
    "youtubeId": "U_xf1_PWgjE",
    "isPodcast": true,
    "category": "Education"
  },
  {
    "id": "yt-podcast-ANdL75NRtro",
    "title": "What is the best advice Alia Bhatt has ever received? #jayshetty #podcast #aliabhatt",
    "artist": "Jay Shetty Podcast",
    "album": "Education",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=ANdL75NRtro",
    "coverUrl": "https://i.ytimg.com/vi/ANdL75NRtro/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Episode Resources: https://www.instagram.com/jayshetty https://www.facebook.com/jayshetty/ https://x.com/jayshetty ...",
    "isYoutube": true,
    "youtubeId": "ANdL75NRtro",
    "isPodcast": true,
    "category": "Education"
  },
  {
    "id": "yt-podcast-SwQhKFMxmDY",
    "title": "Change Your Brain: Neuroscientist Dr. Andrew Huberman | Rich Roll Podcast",
    "artist": "Rich Roll",
    "album": "Education",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=SwQhKFMxmDY",
    "coverUrl": "https://i.ytimg.com/vi/SwQhKFMxmDY/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Thanks for watching! Read all about Dr. Andrew Huberman here https://bit.ly/richroll533 Dr. Andrew Huberman is a ...",
    "isYoutube": true,
    "youtubeId": "SwQhKFMxmDY",
    "isPodcast": true,
    "category": "Education"
  },
  {
    "id": "yt-podcast-jfbZqRjgeeg",
    "title": "Full Podcast On @VinVinWorld #viral #podcast #trending #dentist #youtube",
    "artist": "Vin Vin World",
    "album": "Education",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=jfbZqRjgeeg",
    "coverUrl": "https://i.ytimg.com/vi/jfbZqRjgeeg/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Highly engaging Education discussion.",
    "isYoutube": true,
    "youtubeId": "jfbZqRjgeeg",
    "isPodcast": true,
    "category": "Education"
  },
  {
    "id": "yt-podcast-XzeLupTvj5I",
    "title": "😂‼️ Full episode is out! Watch in its entirety below! | What Now? with Trevor Noah Podcast",
    "artist": "Trevor Noah",
    "album": "Education",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=XzeLupTvj5I",
    "coverUrl": "https://i.ytimg.com/vi/XzeLupTvj5I/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Highly engaging Education discussion.",
    "isYoutube": true,
    "youtubeId": "XzeLupTvj5I",
    "isPodcast": true,
    "category": "Education"
  },
  {
    "id": "yt-podcast-bh7jRjyIg5c",
    "title": "The Learning Pyramid",
    "artist": "Vinh Giang",
    "album": "Education",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=bh7jRjyIg5c",
    "coverUrl": "https://i.ytimg.com/vi/bh7jRjyIg5c/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Whether these numbers are accurate or not... in my experience as a communication skills and public speaking teacher, this is very ...",
    "isYoutube": true,
    "youtubeId": "bh7jRjyIg5c",
    "isPodcast": true,
    "category": "Education"
  },
  {
    "id": "yt-podcast-qt0BXg4eGu0",
    "title": "\"Top 3 Podcasts Every Student Must watch To! 🎧 #StudentLife #Podcasts #Learning\"",
    "artist": "MSJ GYAN",
    "album": "Education",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=qt0BXg4eGu0",
    "coverUrl": "https://i.ytimg.com/vi/qt0BXg4eGu0/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Unlock your full potential with our top three must-listen podcasts for students! Whether you're looking to boost your study skills, get ...",
    "isYoutube": true,
    "youtubeId": "qt0BXg4eGu0",
    "isPodcast": true,
    "category": "Education"
  },
  {
    "id": "yt-podcast-xAt1xcC6qfM",
    "title": "Bill Gates on India, Billion-Dollar Business Opportunities, PM Modi & Children | FO335 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Education",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=xAt1xcC6qfM",
    "coverUrl": "https://i.ytimg.com/vi/xAt1xcC6qfM/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Visit Website: https://www.gatesfoundation.org/ -------------- Guest Suggestion Form: https://forms.gle/bnaeY3FpoFU9ZjA47 ...",
    "isYoutube": true,
    "youtubeId": "xAt1xcC6qfM",
    "isPodcast": true,
    "category": "Education"
  },
  {
    "id": "yt-podcast-Pb60KdHDGlQ",
    "title": "Morning News NOW Full Episode – June 3",
    "artist": "NBC News",
    "album": "News",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=Pb60KdHDGlQ",
    "coverUrl": "https://i.ytimg.com/vi/Pb60KdHDGlQ/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Ballots are still being counted in several key primary elections, escalation rises in the Middle East as Iran strikes Kuwait's airport ...",
    "isYoutube": true,
    "youtubeId": "Pb60KdHDGlQ",
    "isPodcast": true,
    "category": "News"
  },
  {
    "id": "yt-podcast-t0RwmQTY36Y",
    "title": "Deep Secret | Full Episode",
    "artist": "48 Hours",
    "album": "News",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=t0RwmQTY36Y",
    "coverUrl": "https://i.ytimg.com/vi/t0RwmQTY36Y/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Was a missing teenager a runaway or the victim of a serial killer? \"48 Hours Mystery\" correspondent Erin Moriarty reports in this ...",
    "isYoutube": true,
    "youtubeId": "t0RwmQTY36Y",
    "isPodcast": true,
    "category": "News"
  },
  {
    "id": "yt-podcast-bxa4o5O7vQA",
    "title": "Morning News NOW Full Episode - June 1",
    "artist": "NBC News",
    "album": "News",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=bxa4o5O7vQA",
    "coverUrl": "https://i.ytimg.com/vi/bxa4o5O7vQA/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Iran claims it attacked an American air base as the U.S. carries out what it calls self-defense strikes on Iranian targets, former vice ...",
    "isYoutube": true,
    "youtubeId": "bxa4o5O7vQA",
    "isPodcast": true,
    "category": "News"
  },
  {
    "id": "yt-podcast-HRaDf9aNkc8",
    "title": "Andrew Scott (Full Episode) | Conan O'Brien Needs A Friend",
    "artist": "Team Coco",
    "album": "News",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=HRaDf9aNkc8",
    "coverUrl": "https://i.ytimg.com/vi/HRaDf9aNkc8/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Tá áthas ar Andrew Scott about being Conan O'Brien's friend. Andrew sits down with Conan to discuss his latest film Pressure, the ...",
    "isYoutube": true,
    "youtubeId": "HRaDf9aNkc8",
    "isPodcast": true,
    "category": "News"
  },
  {
    "id": "yt-podcast-k-ibxN2Ysb8",
    "title": "NBC Nightly News Full Episode - June 1",
    "artist": "NBC News",
    "album": "News",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=k-ibxN2Ysb8",
    "coverUrl": "https://i.ytimg.com/vi/k-ibxN2Ysb8/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Tonight: President Trump said he would be 'okay' if the Iranian regime refused to return to talks. The administration also appeared ...",
    "isYoutube": true,
    "youtubeId": "k-ibxN2Ysb8",
    "isPodcast": true,
    "category": "News"
  },
  {
    "id": "yt-podcast-9tw8bK3Qhb4",
    "title": "Full Episode: TODAY Show - June 2",
    "artist": "NBC News",
    "album": "News",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=9tw8bK3Qhb4",
    "coverUrl": "https://i.ytimg.com/vi/9tw8bK3Qhb4/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Watch TODAY on NBC Weekdays at 7am local time. » Subscribe to TODAY: https://www.youtube.com/@TODAY TODAY brings ...",
    "isYoutube": true,
    "youtubeId": "9tw8bK3Qhb4",
    "isPodcast": true,
    "category": "News"
  },
  {
    "id": "yt-podcast-TmIyXArR9wU",
    "title": "NBC Nightly News Full Episode - June 2",
    "artist": "NBC News",
    "album": "News",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=TmIyXArR9wU",
    "coverUrl": "https://i.ytimg.com/vi/TmIyXArR9wU/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Tonight: Former Reality TV star Spencer Pratt takes on LA Mayor Karen Bass and Progressive Council Woman Nithya Raman ...",
    "isYoutube": true,
    "youtubeId": "TmIyXArR9wU",
    "isPodcast": true,
    "category": "News"
  },
  {
    "id": "yt-podcast-hP8AaX9Cl7o",
    "title": "PBS News Hour full episode, June 2, 2026",
    "artist": "PBS NewsHour",
    "album": "News",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=hP8AaX9Cl7o",
    "coverUrl": "https://i.ytimg.com/vi/hP8AaX9Cl7o/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Tuesday on the News Hour, Trump taps housing official Bill Pulte as acting director of national intelligence despite having no ...",
    "isYoutube": true,
    "youtubeId": "hP8AaX9Cl7o",
    "isPodcast": true,
    "category": "News"
  },
  {
    "id": "yt-podcast-wxgJc30ihtc",
    "title": "Morning News NOW Full Episode – June 2",
    "artist": "NBC News",
    "album": "News",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=wxgJc30ihtc",
    "coverUrl": "https://i.ytimg.com/vi/wxgJc30ihtc/hqdefault.jpg",
    "genre": "Podcast",
    "description": "The Trump administration signals plans to abandon a $1.8 billion “anti-weaponization” fund after bipartisan backlash, voters ...",
    "isYoutube": true,
    "youtubeId": "wxgJc30ihtc",
    "isPodcast": true,
    "category": "News"
  },
  {
    "id": "yt-podcast-RkVYiKpHxnU",
    "title": "PBS News Hour full episode, June 1, 2026",
    "artist": "PBS NewsHour",
    "album": "News",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=RkVYiKpHxnU",
    "coverUrl": "https://i.ytimg.com/vi/RkVYiKpHxnU/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Monday on the News Hour, the Justice Department hits pause on its plans for a so-called \"anti-weaponization\" fund for people ...",
    "isYoutube": true,
    "youtubeId": "RkVYiKpHxnU",
    "isPodcast": true,
    "category": "News"
  },
  {
    "id": "yt-podcast-924SqgEZqec",
    "title": "England vs New Zealand Test series PREVIEW! | Sky Sports Cricket Podcast",
    "artist": "Sky Sports Cricket",
    "album": "Sports",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=924SqgEZqec",
    "coverUrl": "https://i.ytimg.com/vi/924SqgEZqec/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Subscribe to Sky Sports Cricket: http://bit.ly/SubscribeSkyCricket ▻ Watch Sky Sports: https://bit.ly/BuySkySports Micheal Atherton ...",
    "isYoutube": true,
    "youtubeId": "924SqgEZqec",
    "isPodcast": true,
    "category": "Sports"
  },
  {
    "id": "yt-podcast-gHQo3UafM54",
    "title": "Sunil Chhetri On Indian Football, Retirement, Love Life, Family & Virat Kohli | FO 223 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Sports",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=gHQo3UafM54",
    "coverUrl": "https://i.ytimg.com/vi/gHQo3UafM54/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Order 'Build, Don't Talk' (in English) here: https://amzn.eu/d/eCfijRu Order 'Build Don't Talk' (in Hindi) here: ...",
    "isYoutube": true,
    "youtubeId": "gHQo3UafM54",
    "isPodcast": true,
    "category": "Sports"
  },
  {
    "id": "yt-podcast-Jqo1BM0TfBY",
    "title": "Mindset of a Champion ft. Virat Kohli | RCB Podcast: Bold and Beyond | IPL 2025",
    "artist": "Royal Challengers Bengaluru",
    "album": "Sports",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=Jqo1BM0TfBY",
    "coverUrl": "https://i.ytimg.com/vi/Jqo1BM0TfBY/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Let's get into the mind of Virat Kohli, what makes him the GOAT, how he looks back at this 18 year journey with RCB, the ...",
    "isYoutube": true,
    "youtubeId": "Jqo1BM0TfBY",
    "isPodcast": true,
    "category": "Sports"
  },
  {
    "id": "yt-podcast-lmjQ4ymSqnw",
    "title": "Yashasvi Jaiswal Podcast: Mindset, Struggles, Team India, Cricket & IPL | FO416 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Sports",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=lmjQ4ymSqnw",
    "coverUrl": "https://i.ytimg.com/vi/lmjQ4ymSqnw/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Check out ASUS ExpertBook P Series: https://www.flipkart.com/bbd-eb-sale-at-store -------------- Guest Suggestion Form: ...",
    "isYoutube": true,
    "youtubeId": "lmjQ4ymSqnw",
    "isPodcast": true,
    "category": "Sports"
  },
  {
    "id": "yt-podcast-ke3Pb9_oMrg",
    "title": "⁠How Michael Phelps Built a Champion Mindset: Obsession & Discipline | FO458 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Sports",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=ke3Pb9_oMrg",
    "coverUrl": "https://i.ytimg.com/vi/ke3Pb9_oMrg/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Guest Suggestion Form: https://forms.gle/bnaeY3FpoFU9ZjA47 -------------- Design Your Own Podcast Episode: ...",
    "isYoutube": true,
    "youtubeId": "ke3Pb9_oMrg",
    "isPodcast": true,
    "category": "Sports"
  },
  {
    "id": "yt-podcast-QoAoefT3VJc",
    "title": "Novak Djokovic REVEALS His Secret Mindset Shift That ENDS Self-Doubt...",
    "artist": "Jay Shetty Podcast",
    "album": "Sports",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=QoAoefT3VJc",
    "coverUrl": "https://i.ytimg.com/vi/QoAoefT3VJc/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Have you ever doubted yourself? Has self-doubt ever held you back? Today, Jay welcomes back tennis GOAT, Olympic Gold ...",
    "isYoutube": true,
    "youtubeId": "QoAoefT3VJc",
    "isPodcast": true,
    "category": "Sports"
  },
  {
    "id": "yt-podcast-2jUNkslI9gE",
    "title": "IPL’s Biggest Moments, Hardik Pandya's Struggle, Auctions, MS Dhoni & Cricket | FO339 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Sports",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=2jUNkslI9gE",
    "coverUrl": "https://i.ytimg.com/vi/2jUNkslI9gE/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Guest Suggestion Form: https://forms.gle/bnaeY3FpoFU9ZjA47 -------------- Disclaimer: This video is intended solely for ...",
    "isYoutube": true,
    "youtubeId": "2jUNkslI9gE",
    "isPodcast": true,
    "category": "Sports"
  },
  {
    "id": "yt-podcast-zMXn5_nbGJs",
    "title": "Raj Shamani x MS Dhoni - Podcast | @Ssc_Youth_Connect  #Shorts",
    "artist": "Raj Shamani",
    "album": "Sports",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=zMXn5_nbGJs",
    "coverUrl": "https://i.ytimg.com/vi/zMXn5_nbGJs/hqdefault.jpg",
    "genre": "Podcast",
    "description": "I can't believe that, this happened with me The kid in me, the 11-year-old Raj who saw India winning for the first time is crying ...",
    "isYoutube": true,
    "youtubeId": "zMXn5_nbGJs",
    "isPodcast": true,
    "category": "Sports"
  },
  {
    "id": "yt-podcast-2xzIc-sY-cA",
    "title": "Virat Kohli on Athlete Mindset, Leadership Pressure & Delhi Days",
    "artist": "Jatin Sapru",
    "album": "Sports",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=2xzIc-sY-cA",
    "coverUrl": "https://i.ytimg.com/vi/2xzIc-sY-cA/hqdefault.jpg",
    "genre": "Podcast",
    "description": "This video was recorded on 5 November, 2023. Courtesy: Let There Be Sport @PUMA Join Jatin Sapru as he sits down with Virat ...",
    "isYoutube": true,
    "youtubeId": "2xzIc-sY-cA",
    "isPodcast": true,
    "category": "Sports"
  },
  {
    "id": "yt-podcast-J0TkybCKaJI",
    "title": "Shikhar Dhawan on Pakistan, Virat Kohli, Rohit Sharma, Relationships & Divorce | FO414 Raj Shamani",
    "artist": "Raj Shamani",
    "album": "Sports",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=J0TkybCKaJI",
    "coverUrl": "https://i.ytimg.com/vi/J0TkybCKaJI/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Check out ASUS ExpertBook P Series: https://www.flipkart.com/bbd-eb-sale-at-store -------------- Guest Suggestion Form: ...",
    "isYoutube": true,
    "youtubeId": "J0TkybCKaJI",
    "isPodcast": true,
    "category": "Sports"
  },
  {
    "id": "yt-podcast-O0CuYUQHoaU",
    "title": "Rakhi Sawant EXPOSES Bollywood Ft. Samay Raina | Bold Scenes, Salman Khan, Farah Khan | Podcast",
    "artist": "Hindi Rush",
    "album": "Entertainment",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=O0CuYUQHoaU",
    "coverUrl": "https://i.ytimg.com/vi/O0CuYUQHoaU/hqdefault.jpg",
    "genre": "Podcast",
    "description": "In this hindi Podcast, Rakhi Sawant opens up like never before! From her struggle story to her bond with Salman Khan, Farah ...",
    "isYoutube": true,
    "youtubeId": "O0CuYUQHoaU",
    "isPodcast": true,
    "category": "Entertainment"
  },
  {
    "id": "yt-podcast-O46vDMP57Uk",
    "title": "Watch full episode only unfiltered with Ajaz khan.#ytshorts #ajazkhan #podcast",
    "artist": "Ajaz Khan Official",
    "album": "Entertainment",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=O46vDMP57Uk",
    "coverUrl": "https://i.ytimg.com/vi/O46vDMP57Uk/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Highly engaging Entertainment discussion.",
    "isYoutube": true,
    "youtubeId": "O46vDMP57Uk",
    "isPodcast": true,
    "category": "Entertainment"
  },
  {
    "id": "yt-podcast-OcISVEh1jyw",
    "title": "Priyanka Chopra on Self Confidence, Entrepreneurship, Family & Success | The Ranveer Show 256",
    "artist": "BeerBiceps",
    "album": "Entertainment",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=OcISVEh1jyw",
    "coverUrl": "https://i.ytimg.com/vi/OcISVEh1jyw/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Check out 'Anomaly X Nykaa' products here: https://www.nykaa.com/brands/anomaly/c/24797 Check out my Meditation app: ...",
    "isYoutube": true,
    "youtubeId": "OcISVEh1jyw",
    "isPodcast": true,
    "category": "Entertainment"
  },
  {
    "id": "yt-podcast-ZxLQy7JMsio",
    "title": "Bollywood secrets with Page 3 journalist Simi Chandoke | Verinteresting Podcast Ep. 1",
    "artist": "Verinteresting",
    "album": "Entertainment",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=ZxLQy7JMsio",
    "coverUrl": "https://i.ytimg.com/vi/ZxLQy7JMsio/hqdefault.jpg",
    "genre": "Podcast",
    "description": "This podcast gives an insight view of the Bollywood Page 3 parties by Entertainment Journalist Simi Chandoke. Simi has closely ...",
    "isYoutube": true,
    "youtubeId": "ZxLQy7JMsio",
    "isPodcast": true,
    "category": "Entertainment"
  },
  {
    "id": "yt-podcast-U_xf1_PWgjE",
    "title": "Raj Shamani's brain test 😱 #braintest #rajshamani #mindset #motivation #podcast",
    "artist": "Ajay Inspiration",
    "album": "Entertainment",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=U_xf1_PWgjE",
    "coverUrl": "https://i.ytimg.com/vi/U_xf1_PWgjE/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Raj Shamani's brain test #braintest #rajshamani #mindset #motivation #podcast.",
    "isYoutube": true,
    "youtubeId": "U_xf1_PWgjE",
    "isPodcast": true,
    "category": "Entertainment"
  },
  {
    "id": "yt-podcast--lFAIxq8kaY",
    "title": "I Regret Inviting Ravi Gupta on My Podcast!! | PGX#88 @raviguptacomedy",
    "artist": "Prakhar Gupta",
    "album": "Entertainment",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=-lFAIxq8kaY",
    "coverUrl": "https://i.ytimg.com/vi/-lFAIxq8kaY/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Master the Most Useful Human Skill: https://bit.ly/3Vdu64A Listen to this podcast and other episodes of The Prakhar Gupta ...",
    "isYoutube": true,
    "youtubeId": "-lFAIxq8kaY",
    "isPodcast": true,
    "category": "Entertainment"
  },
  {
    "id": "yt-podcast-M7Q6eRx_k8Q",
    "title": "Live Show Mein Jinnat Ko Bulaya, Ibratnaak Mout Or Dubai Mein Jinnat Ka Waqiya | DAR-HAQEEQAT EP-20",
    "artist": "Metatainment",
    "album": "Entertainment",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=M7Q6eRx_k8Q",
    "coverUrl": "https://i.ytimg.com/vi/M7Q6eRx_k8Q/hqdefault.jpg",
    "genre": "Podcast",
    "description": "darhaqeeqat #liveshowmeinjinnat #ibratnaakwakiya #jinnat #azlanshah #podcast Send your stories via a voice note on ...",
    "isYoutube": true,
    "youtubeId": "M7Q6eRx_k8Q",
    "isPodcast": true,
    "category": "Entertainment"
  },
  {
    "id": "yt-podcast-MCAPRAEG9wk",
    "title": "Unhinged -- Reddit Stories -- FULL EPISODE",
    "artist": "Two Hot Takes",
    "album": "Entertainment",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=MCAPRAEG9wk",
    "coverUrl": "https://i.ytimg.com/vi/MCAPRAEG9wk/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Two Hot Takes host, Morgan, is joined by guest co-hosts Justin and Lauren. This is exactly what Lauren wanted.. the wild stories.",
    "isYoutube": true,
    "youtubeId": "MCAPRAEG9wk",
    "isPodcast": true,
    "category": "Entertainment"
  },
  {
    "id": "yt-podcast-R3L6edOy5bY",
    "title": "Fake Podcast with Middle Class Baap | राजेश अंकल | Season Finale EP-10",
    "artist": "Satish Ray",
    "album": "Entertainment",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=R3L6edOy5bY",
    "coverUrl": "https://i.ytimg.com/vi/R3L6edOy5bY/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Middle Class Baap Rajesh uncle comes on Fake Podcast and he is interviewed by Prashn Kumar on desi parenting, enjoy the ...",
    "isYoutube": true,
    "youtubeId": "R3L6edOy5bY",
    "isPodcast": true,
    "category": "Entertainment"
  },
  {
    "id": "yt-podcast-mhu8V2ww3wQ",
    "title": "Rani Pari Uncensored: Bold & Hilarious Podcast with Ullu Actress | Gap-Shap With Shyna Khatri",
    "artist": "Shyna Khatri",
    "album": "Entertainment",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=mhu8V2ww3wQ",
    "coverUrl": "https://i.ytimg.com/vi/mhu8V2ww3wQ/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Welcome to another exciting episode of *Gap-Shap with Shyna Khatri*! This time, we have the sensational and bold Ullu actress, ...",
    "isYoutube": true,
    "youtubeId": "mhu8V2ww3wQ",
    "isPodcast": true,
    "category": "Entertainment"
  },
  {
    "id": "yt-podcast-jpYHVyDyOlQ",
    "title": "Krishna Ke Raaz - Gen-Z Spirituality Podcast",
    "artist": "Ranveer Allahbadia",
    "album": "Spirituality",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=jpYHVyDyOlQ",
    "coverUrl": "https://i.ytimg.com/vi/jpYHVyDyOlQ/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Check out BeerBiceps SkillHouse's YouTube 1O1 Course - https://youtube.beerbicepsskillhouse.in/youtube-101 Share your guest ...",
    "isYoutube": true,
    "youtubeId": "jpYHVyDyOlQ",
    "isPodcast": true,
    "category": "Spirituality"
  },
  {
    "id": "yt-podcast-FRTpI2Gu1KA",
    "title": "Indian Monk Explains Bhagawad Gita In 7 Minutes | Gaur Gopal Das on TRS",
    "artist": "BeerBiceps",
    "album": "Spirituality",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=FRTpI2Gu1KA",
    "coverUrl": "https://i.ytimg.com/vi/FRTpI2Gu1KA/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Watch The Full Episode Here : https://youtu.be/sBH-ngpL0zo Watch Our PODCAST CLIPS (Highlights of our podcast) ...",
    "isYoutube": true,
    "youtubeId": "FRTpI2Gu1KA",
    "isPodcast": true,
    "category": "Spirituality"
  },
  {
    "id": "yt-podcast-JiDSy4t1Nz8",
    "title": "KARMA’s GAME PLAN: Why Do We Go Through Tough Times explained by Guru Sakala Maa | TRS",
    "artist": "BeerBiceps",
    "album": "Spirituality",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=JiDSy4t1Nz8",
    "coverUrl": "https://i.ytimg.com/vi/JiDSy4t1Nz8/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Check Out Books Written by Guru Sakala Maa: ...",
    "isYoutube": true,
    "youtubeId": "JiDSy4t1Nz8",
    "isPodcast": true,
    "category": "Spirituality"
  },
  {
    "id": "yt-podcast-Yiaatr-Noh0",
    "title": "The Power of Being Alone | Sadhguru Jaggi Vasudev",
    "artist": "Sadhguru",
    "album": "Spirituality",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=Yiaatr-Noh0",
    "coverUrl": "https://i.ytimg.com/vi/Yiaatr-Noh0/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Sadhguru talks about the importance of learning to be alone if we want togetherness to be rich and rewarding. To watch this video ...",
    "isYoutube": true,
    "youtubeId": "Yiaatr-Noh0",
    "isPodcast": true,
    "category": "Spirituality"
  },
  {
    "id": "yt-podcast-jQ6ymAcX7B0",
    "title": "Mystery of Himalaya & Kailash, 2026 Future Predictions, Shambhala, Astral Cities | Swami YO | ST 195",
    "artist": "Supertalks by themovingship",
    "album": "Spirituality",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=jQ6ymAcX7B0",
    "coverUrl": "https://i.ytimg.com/vi/jQ6ymAcX7B0/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Guest Suggestion Form: https://forms.gle/EcXwKgHsxYEmS85q8 --------- Support Raghav's NGO at ...",
    "isYoutube": true,
    "youtubeId": "jQ6ymAcX7B0",
    "isPodcast": true,
    "category": "Spirituality"
  },
  {
    "id": "yt-podcast-vsax8o_X660",
    "title": "Akshat Gupta Podcast 2025: Mahabharat Secrets, Ramayan, ShivJi, Aghori, Kailash Parvat, Karna, Kalki",
    "artist": "PINKVILLA",
    "album": "Spirituality",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=vsax8o_X660",
    "coverUrl": "https://i.ytimg.com/vi/vsax8o_X660/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Welcome to the Akshat Gupta Podcast 2025, where we delve into the fascinating tales and timeless wisdom from ancient Indian ...",
    "isYoutube": true,
    "youtubeId": "vsax8o_X660",
    "isPodcast": true,
    "category": "Spirituality"
  },
  {
    "id": "yt-podcast-Zs6VeNVnTac",
    "title": "Secrets of Ramayan: Shambhala Mystery, Time Travel REAL story & Hanuman Ji | Eeshaan Mahesh | ST-139",
    "artist": "Supertalks by themovingship",
    "album": "Spirituality",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=Zs6VeNVnTac",
    "coverUrl": "https://i.ytimg.com/vi/Zs6VeNVnTac/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Support Raghav's NGO at https://skchildrenfoundation.org/donation/ - In this powerful spiritual episode, host Raghav Sharma ...",
    "isYoutube": true,
    "youtubeId": "Zs6VeNVnTac",
    "isPodcast": true,
    "category": "Spirituality"
  },
  {
    "id": "yt-podcast-QMtdOS8W3Fc",
    "title": "Krishna’s Advice For All Your Problems | Gita Explained - Gauranga Das with GunjanShouts",
    "artist": "GunjanShouts",
    "album": "Spirituality",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=QMtdOS8W3Fc",
    "coverUrl": "https://i.ytimg.com/vi/QMtdOS8W3Fc/hqdefault.jpg",
    "genre": "Podcast",
    "description": "In this powerful and thought-provoking podcast of GunjanShouts, we sit down with Gauranga Das, spiritual leader, monk, and ...",
    "isYoutube": true,
    "youtubeId": "QMtdOS8W3Fc",
    "isPodcast": true,
    "category": "Spirituality"
  },
  {
    "id": "yt-podcast-F93MsW_vXC8",
    "title": "Secrets of Kailash: Shiva, Miracles & Real Experiences | Yuvraj Srivastava | Supertalks हिंदी -155",
    "artist": "Supertalks by themovingship",
    "album": "Spirituality",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=F93MsW_vXC8",
    "coverUrl": "https://i.ytimg.com/vi/F93MsW_vXC8/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Support Raghav's NGO at https://skchildrenfoundation.org/donation/ - In this episode, our host Raghav Sharma sits down with ...",
    "isYoutube": true,
    "youtubeId": "F93MsW_vXC8",
    "isPodcast": true,
    "category": "Spirituality"
  },
  {
    "id": "yt-podcast-abDCaOEI3mc",
    "title": "TRUTH About Aghoris Revealed By Avdhoot Alakhram | 400 Year Sadhna, Rituals, Myths, Facts | TRS",
    "artist": "Ranveer Allahbadia",
    "album": "Spirituality",
    "duration": 1800,
    "url": "https://www.youtube.com/watch?v=abDCaOEI3mc",
    "coverUrl": "https://i.ytimg.com/vi/abDCaOEI3mc/hqdefault.jpg",
    "genre": "Podcast",
    "description": "Check out BeerBiceps SkillHouse Courses Here - https://www.bbskillhouse.com For all BeerBiceps vlog content Watch Life Of ...",
    "isYoutube": true,
    "youtubeId": "abDCaOEI3mc",
    "isPodcast": true,
    "category": "Spirituality"
  }
];

export interface GenreItem {
  id: string;
  name: string;
  coverUrl: string;
  description: string;
  trackId: string; // launching track associated
  count?: number;
  hue?: string;
}

export const GENRES: GenreItem[] = [
  {
    id: 'bollywood',
    name: 'Bollywood & Sufi',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60',
    description: 'Soul-stirring classical, instrumental, and pop masterworks of South Asia.',
    trackId: 'ar-rahman-dil-se-re'
  },
  {
    id: 'pop',
    name: 'Global Pop',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=60',
    description: 'Chart-topping melodies, upbeat rhythms, and shiny synth waves.',
    trackId: 'the-weeknd-blinding-lights'
  },
  {
    id: 'acoustic',
    name: 'Acoustic & Indie',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60',
    description: 'Intimate vocal recordings, delicate fingerpicking, and pure sentiment.',
    trackId: 'prateek-kuhad-cold-mess'
  },
  {
    id: 'indierock',
    name: 'Acoustic Indie Rock',
    coverUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=500&auto=format&fit=crop&q=60',
    description: 'Emotional twilight cords, anthemic choruses, and stellar guitars.',
    trackId: 'local-train-choo-lo'
  },
  {
    id: 'dance',
    name: 'Dance',
    coverUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDbLO5M-JSYky6Iau-JJmkbDAnuGRiV3QbvMbQB0dJ0U5uFw3HkznJX1yVrpfssJG8Mc0MDJqnVsW7EIf5Jtb2ZqJKMg8oPUETZ0YsX7zI8MfuJhC-30RL2Gdkrnp7RZAC3GAmecEY4Uxb3ImOutOo6fBjzKXnY4NEfpZ4SY2fURslwXkrojk8aKfh2iqehrrR8Dle7WXf4Qg59QwId-B33n89zYmifXxRfOQNH7RIQed40JVQm4cYRGdtMkk1YH3Cux6OtGHgan_7V',
    description: 'Vibrant gradients with deep rhythms.',
    trackId: 'space-station-deep-house'
  },
  {
    id: 'techno',
    name: 'Techno',
    coverUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAM_HidYNpSkD-99bGX1bqI6Bdb335tQPSSC_8iOj3a0SPrmlrP8ll_vbZTLDXi_Zbq6rio89jjmRIs1sFyk4ZlEqE8Vv0se1u2-WieCbdCJnq-H6qYcLLCobo-Eu_4LdtsCtAiWUFW8l6OafJoFA-qwtveN58dVx6Gexr3-gYfBhKdoeoUoLBprOz1UqLB0qtd8QesT3iSBj5BywuPoa1b4zwN4ZuIgqTkhC5AyyWh6wUXz7iZJTHu2l2yXYfuwP1X9Y1Wd0DuCANE',
    description: 'Pulsing lasers in dark warehouse clubs.',
    trackId: 'club-life-electronic'
  },
  {
    id: 'rock',
    name: 'Rock',
    coverUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoTi5HZSgy7kr3S41qVT2b7uQnZxfUNG8yNfIcdHwuSvdhGM5kR7gy0wzMHMf2yxwAizLmVk4RctFOVTOvkmWA2QN6ldiquD-Y6wHT3zeJa6gZJYAP_k1s4AYZTgtArWQuBjuwsprNhv7a_9mg24uZj5GNWBtnAq-D5QALeFcNMj8A4tRi_x7dPHFTcA-Mgj7vQUz-cC8aIkMY-Y-xwo9eBw-6DLqVe8JlhDnMwYyJ_44LIGElS9Dia4UjzO4egVpU7J5lINK6ptG9',
    description: 'Gritty strings and raw, heavy energy.',
    trackId: 'live-ocean-stage'
  },
  {
    id: 'chill',
    name: 'Chill',
    coverUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAryA8v1AJHIa5ko_FiF-HNBzBsg6FRwmUC2kwHWO1HbP6Dsw-r4UdM3FjUPLJ1rwInUv3-79R0Ceaba0xzmpzr8a9JjZpRVULUJgnGWCA2TzN0MeslDp6xIGHfwfNQHiFNHMeATN-3h7bgjGCwxS-B4bYr1bFDbqF6kPYftNdnOG6Ynw3eLdYyb21Xe6wJDWGaC6YGqaDsbSkHVgZbx-bvXWK0z--y-vDviWB8de2t-JjgcEAQZ_jCJrBFkqGt_CWBt1afp8_DVi1n',
    description: 'Studio consoles and smooth lofi beats.',
    trackId: 'retro-vintage-mix'
  }
];

export const HEADPHONE_IMAGE = 'https://lh3.googleusercontent.com/aida-public/AB6AXuAQuOn_DKipx7303Sfh4j9u0l7fZxmQ1_fzhuBOcj2oMuAU5eW_1YltrwQDDuHT8u8KcR39z9dJaD6imcHcyeKlg8hKZRUFtnLVfCFjMAg-4wPkdAEsQgNzOs6AAMfuGDRMfYfPJNCc-_tAmr6RJO0vmRpXwl1KptXDWJ-pl3ekv4HSXTnNMUtcMukl-8F2FzgdK8mLC7B9ST74OLlMERhV4sI8QgoGvLBiRtimYdNtYp4WqYCgBO6QItGPL98r3V6VhTi5a2_5VhV7';
export const USER_AVATAR_IMAGE = 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk9YJ1ywYpPR4vCRKVT0d2ZDUV36OGLhqn9teFILC3hFVP-EN-n5xijYHuV_8MRiaKqNeQeecQAKbAXgVPp1b_VLI3sgJpNUN3ViZiq5VL6K4HiSIfgLFZoXb59Xfe140psNlaXbD7K1DgnirUfzCAiCQH6tiWdLLc4obeVaBqEk-QPnnxqwXEQcG8TxMjnC1RkmxShfG9AN7ezkb-PoMk_HYTotZ3yu3rK_23O0kVRuegQr6K6pJS1zijj42SQ--46GRRryEoGEpo';
export const FEATURED_TRENDING_IMAGE = 'https://lh3.googleusercontent.com/aida-public/AB6AXuD1vdoux6XOhMdkfKhbtS_PnB-_ldAtmr3X95ccsY32Xuvz0m8RaTumiWn_TyMuzJSxkPNu9ymEZQgnrhiEwjE-19clLyXF5MfnWrBeFpXsV5KTLVV1XRF-Zxdi9-IPOHGllF382-8kX6cBqUD3-ItmJdeNb4xaEY0Jb8D1rUNzOH8ip31RPE0MoJHjmdOJcsoTuSB461_TIC15czbyYy4FKzjMgcZFW4VejxXIXnhRsbmDzDJGQ9UxFe5eES5ZLLt0nhGWnjvwI4MZ';
