export const TOP_LYRIC_TRACKS = [
  {
    id: "yt-4NRXx6U8ABQ",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    duration: 200,
    url: "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
    coverUrl: "https://img.youtube.com/vi/4NRXx6U8ABQ/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "4NRXx6U8ABQ",
    hasLyrics: true
  },
  {
    id: "yt-JGwWNGJdvx8",
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "Divide",
    duration: 233,
    url: "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    coverUrl: "https://img.youtube.com/vi/JGwWNGJdvx8/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "JGwWNGJdvx8",
    hasLyrics: true
  },
  {
    id: "yt-2Vv-BfVoq4g",
    title: "Perfect",
    artist: "Ed Sheeran",
    album: "Divide",
    duration: 263,
    url: "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    coverUrl: "https://img.youtube.com/vi/2Vv-BfVoq4g/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "2Vv-BfVoq4g",
    hasLyrics: true
  },
  {
    id: "yt-zABLecsR5UE",
    title: "Someone You Loved",
    artist: "Lewis Capaldi",
    album: "Divinely Uninspired",
    duration: 182,
    url: "https://www.youtube.com/watch?v=zABLecsR5UE",
    coverUrl: "https://img.youtube.com/vi/zABLecsR5UE/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "zABLecsR5UE",
    hasLyrics: true
  },
  {
    id: "yt-kPa7bsKwL-c",
    title: "Die With A Smile",
    artist: "Lady Gaga, Bruno Mars",
    album: "Single",
    duration: 251,
    url: "https://www.youtube.com/watch?v=kPa7bsKwL-c",
    coverUrl: "https://img.youtube.com/vi/kPa7bsKwL-c/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "kPa7bsKwL-c",
    hasLyrics: true
  },
  {
    id: "yt-H5v3kku4y6Q",
    title: "As It Was",
    artist: "Harry Styles",
    album: "Harry's House",
    duration: 167,
    url: "https://www.youtube.com/watch?v=H5v3kku4y6Q",
    coverUrl: "https://img.youtube.com/vi/H5v3kku4y6Q/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "H5v3kku4y6Q",
    hasLyrics: true
  },
  {
    id: "yt-mRD0-GxqHVo",
    title: "Heat Waves",
    artist: "Glass Animals",
    album: "Dreamland",
    duration: 238,
    url: "https://www.youtube.com/watch?v=mRD0-GxqHVo",
    coverUrl: "https://img.youtube.com/vi/mRD0-GxqHVo/hqdefault.jpg",
    genre: "Alternative",
    isYoutube: true,
    youtubeId: "mRD0-GxqHVo",
    hasLyrics: true
  },
  {
    id: "yt-yKNxeF4KMsY",
    title: "Yellow",
    artist: "Coldplay",
    album: "Parachutes",
    duration: 266,
    url: "https://www.youtube.com/watch?v=yKNxeF4KMsY",
    coverUrl: "https://img.youtube.com/vi/yKNxeF4KMsY/hqdefault.jpg",
    genre: "Alternative",
    isYoutube: true,
    youtubeId: "yKNxeF4KMsY",
    hasLyrics: true
  },
  {
    id: "yt-wGF7PswOENQ",
    title: "The Night We Met",
    artist: "Lord Huron",
    album: "Strange Trails",
    duration: 208,
    url: "https://www.youtube.com/watch?v=wGF7PswOENQ",
    coverUrl: "https://img.youtube.com/vi/wGF7PswOENQ/hqdefault.jpg",
    genre: "Indie",
    isYoutube: true,
    youtubeId: "wGF7PswOENQ",
    hasLyrics: true
  },
  {
    id: "yt-d5zfMmVbzAY",
    title: "BIRDS OF A FEATHER",
    artist: "Billie Eilish",
    album: "HIT ME HARD AND SOFT",
    duration: 210,
    url: "https://www.youtube.com/watch?v=d5zfMmVbzAY",
    coverUrl: "https://img.youtube.com/vi/d5zfMmVbzAY/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "d5zfMmVbzAY",
    hasLyrics: true
  },
  {
    id: "yt-fJ9rUzIMcZQ",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    duration: 354,
    url: "https://www.youtube.com/watch?v=fJ9rUzIMcZQ",
    coverUrl: "https://img.youtube.com/vi/fJ9rUzIMcZQ/hqdefault.jpg",
    genre: "Rock",
    isYoutube: true,
    youtubeId: "fJ9rUzIMcZQ",
    hasLyrics: true
  },
  {
    id: "yt-rYEDA3JcQqw",
    title: "Rolling in the Deep",
    artist: "Adele",
    album: "21",
    duration: 228,
    url: "https://www.youtube.com/watch?v=rYEDA3JcQqw",
    coverUrl: "https://img.youtube.com/vi/rYEDA3JcQqw/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "rYEDA3JcQqw",
    hasLyrics: true
  },
  {
    id: "yt-hLQl3WQQoQ0",
    title: "Someone Like You",
    artist: "Adele",
    album: "21",
    duration: 285,
    url: "https://www.youtube.com/watch?v=hLQl3WQQoQ0",
    coverUrl: "https://img.youtube.com/vi/hLQl3WQQoQ0/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "hLQl3WQQoQ0",
    hasLyrics: true
  },
  {
    id: "yt-450p7goxZqg",
    title: "All of Me",
    artist: "John Legend",
    album: "Love in the Future",
    duration: 269,
    url: "https://www.youtube.com/watch?v=450p7goxZqg",
    coverUrl: "https://img.youtube.com/vi/450p7goxZqg/hqdefault.jpg",
    genre: "R&B",
    isYoutube: true,
    youtubeId: "450p7goxZqg",
    hasLyrics: true
  },
  {
    id: "yt-bo_efYhYU2A",
    title: "Shallow",
    artist: "Lady Gaga, Bradley Cooper",
    album: "A Star Is Born",
    duration: 216,
    url: "https://www.youtube.com/watch?v=bo_efYhYU2A",
    coverUrl: "https://img.youtube.com/vi/bo_efYhYU2A/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "bo_efYhYU2A",
    hasLyrics: true
  },
  {
    id: "yt-PVjiKRfKpPI",
    title: "Take Me To Church",
    artist: "Hozier",
    album: "Hozier",
    duration: 256,
    url: "https://www.youtube.com/watch?v=PVjiKRfKpPI",
    coverUrl: "https://img.youtube.com/vi/PVjiKRfKpPI/hqdefault.jpg",
    genre: "Alternative",
    isYoutube: true,
    youtubeId: "PVjiKRfKpPI",
    hasLyrics: true
  },
  {
    id: "yt-hT_nvWreIhg",
    title: "Counting Stars",
    artist: "OneRepublic",
    album: "Native",
    duration: 257,
    url: "https://www.youtube.com/watch?v=hT_nvWreIhg",
    coverUrl: "https://img.youtube.com/vi/hT_nvWreIhg/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "hT_nvWreIhg",
    hasLyrics: true
  },
  {
    id: "yt-pB-5XG-DbAA",
    title: "Stay With Me",
    artist: "Sam Smith",
    album: "In the Lonely Hour",
    duration: 172,
    url: "https://www.youtube.com/watch?v=pB-5XG-DbAA",
    coverUrl: "https://img.youtube.com/vi/pB-5XG-DbAA/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "pB-5XG-DbAA",
    hasLyrics: true
  },
  {
    id: "yt-GemKqzILV4w",
    title: "Chasing Cars",
    artist: "Snow Patrol",
    album: "Eyes Open",
    duration: 267,
    url: "https://www.youtube.com/watch?v=GemKqzILV4w",
    coverUrl: "https://img.youtube.com/vi/GemKqzILV4w/hqdefault.jpg",
    genre: "Alternative",
    isYoutube: true,
    youtubeId: "GemKqzILV4w",
    hasLyrics: true
  },
  {
    id: "yt-dvgZvn9IeRo",
    title: "Viva La Vida",
    artist: "Coldplay",
    album: "Viva La Vida",
    duration: 242,
    url: "https://www.youtube.com/watch?v=dvgZvn9IeRo",
    coverUrl: "https://img.youtube.com/vi/dvgZvn9IeRo/hqdefault.jpg",
    genre: "Alternative",
    isYoutube: true,
    youtubeId: "dvgZvn9IeRo",
    hasLyrics: true
  },
  {
    id: "yt-7wtfhZwyrcc",
    title: "Believer",
    artist: "Imagine Dragons",
    album: "Evolve",
    duration: 204,
    url: "https://www.youtube.com/watch?v=7wtfhZwyrcc",
    coverUrl: "https://img.youtube.com/vi/7wtfhZwyrcc/hqdefault.jpg",
    genre: "Rock",
    isYoutube: true,
    youtubeId: "7wtfhZwyrcc",
    hasLyrics: true
  },
  {
    id: "yt-OMOGaugKpzs",
    title: "Every Breath You Take",
    artist: "The Police",
    album: "Synchronicity",
    duration: 253,
    url: "https://www.youtube.com/watch?v=OMOGaugKpzs",
    coverUrl: "https://img.youtube.com/vi/OMOGaugKpzs/hqdefault.jpg",
    genre: "Rock",
    isYoutube: true,
    youtubeId: "OMOGaugKpzs",
    hasLyrics: true
  },
  {
    id: "yt-SlPhMPnQ58k",
    title: "Memories",
    artist: "Maroon 5",
    album: "Memories",
    duration: 189,
    url: "https://www.youtube.com/watch?v=SlPhMPnQ58k",
    coverUrl: "https://img.youtube.com/vi/SlPhMPnQ58k/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "SlPhMPnQ58k",
    hasLyrics: true
  },
  {
    id: "yt-1k8craCGv14",
    title: "Don't Stop Believin'",
    artist: "Journey",
    album: "Escape",
    duration: 250,
    url: "https://www.youtube.com/watch?v=1k8craCGv14",
    coverUrl: "https://img.youtube.com/vi/1k8craCGv14/hqdefault.jpg",
    genre: "Rock",
    isYoutube: true,
    youtubeId: "1k8craCGv14",
    hasLyrics: true
  },
  {
    id: "yt-xwtdhWltSIg",
    title: "Losing My Religion",
    artist: "R.E.M.",
    album: "Out of Time",
    duration: 268,
    url: "https://www.youtube.com/watch?v=xwtdhWltSIg",
    coverUrl: "https://img.youtube.com/vi/xwtdhWltSIg/hqdefault.jpg",
    genre: "Alternative",
    isYoutube: true,
    youtubeId: "xwtdhWltSIg",
    hasLyrics: true
  },
  {
    id: "yt-LjhCEhWiKXk",
    title: "Just The Way You Are",
    artist: "Bruno Mars",
    album: "Doo-Wops & Hooligans",
    duration: 220,
    url: "https://www.youtube.com/watch?v=LjhCEhWiKXk",
    coverUrl: "https://img.youtube.com/vi/LjhCEhWiKXk/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "LjhCEhWiKXk",
    hasLyrics: true
  },
  {
    id: "yt-uJ_1HMmBpuY",
    title: "Riptide",
    artist: "Vance Joy",
    album: "Dream Your Life Away",
    duration: 204,
    url: "https://www.youtube.com/watch?v=uJ_1HMmBpuY",
    coverUrl: "https://img.youtube.com/vi/uJ_1HMmBpuY/hqdefault.jpg",
    genre: "Alternative",
    isYoutube: true,
    youtubeId: "uJ_1HMmBpuY",
    hasLyrics: true
  },
  {
    id: "yt-RBumWgDX_2M",
    title: "Let Her Go",
    artist: "Passenger",
    album: "All the Little Lights",
    duration: 252,
    url: "https://www.youtube.com/watch?v=RBumWgDX_2M",
    coverUrl: "https://img.youtube.com/vi/RBumWgDX_2M/hqdefault.jpg",
    genre: "Folk",
    isYoutube: true,
    youtubeId: "RBumWgDX_2M",
    hasLyrics: true
  },
  {
    id: "yt-rtOvBOTyX00",
    title: "A Thousand Years",
    artist: "Christina Perri",
    album: "The Twilight Saga",
    duration: 285,
    url: "https://www.youtube.com/watch?v=rtOvBOTyX00",
    coverUrl: "https://img.youtube.com/vi/rtOvBOTyX00/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "rtOvBOTyX00",
    hasLyrics: true
  },
  {
    id: "yt-lp-EO5I60KA",
    title: "Thinking Out Loud",
    artist: "Ed Sheeran",
    album: "X",
    duration: 281,
    url: "https://www.youtube.com/watch?v=lp-EO5I60KA",
    coverUrl: "https://img.youtube.com/vi/lp-EO5I60KA/hqdefault.jpg",
    genre: "Pop",
    isYoutube: true,
    youtubeId: "lp-EO5I60KA",
    hasLyrics: true
  }
];
